import { ClaimDocumentCategory } from "@prisma/client";

export interface ClaimFormFile {
  id: string;
  insurerSlug: string;
  insurerName: string;
  categoryLabel: string;
  label: string;
  category: ClaimDocumentCategory;
  href: string;
  sourceUrl: string;
  displayOrder: number;
}

export const claimFormFiles = [
  {
    id: "bohumschool-kyobo-digital-2082cac9-1b1f-4dea-8d39-6dc5f588f381",
    insurerSlug: "kyobo-digital",
    insurerName: "교보라이프플래닛",
    categoryLabel: "보험금청구서류",
    label: "단체 사고보험금 청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/kyobo-life-planet/group-accident-insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/kyobo-life-planet/group-accident-insurance-claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-kyobo-digital-2d4aa7e7-549b-4c2b-b7e0-7155f97f3b56",
    insurerSlug: "kyobo-digital",
    insurerName: "교보라이프플래닛",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/kyobo-life-planet/insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/kyobo-life-planet/insurance-claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-kyobo-life-65e806e7-a190-49e5-9993-fe78a5ac0381",
    insurerSlug: "kyobo-life",
    insurerName: "교보생명",
    categoryLabel: "공통",
    label: "보험금청구서 및 상세동의서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/kyobo/common/claim-form-and-detailed-consent-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/kyobo/common/claim-form-and-detailed-consent-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-tongyang-life-da2530a7-c228-4476-98fa-d20b8cfe1820",
    insurerSlug: "tongyang-life",
    insurerName: "동양생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서 및 동의서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/dongyang/claim-form-and-consent-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/dongyang/claim-form-and-consent-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-tongyang-life-b0ad9e6f-919a-40b0-91ab-65d240018b64",
    insurerSlug: "tongyang-life",
    insurerName: "동양생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서 및 동의서(큰글씨용)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/dongyang/claim-form-and-consent-form--large-print-.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/dongyang/claim-form-and-consent-form-(large-print).pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-tongyang-life-5334262a-2bb5-4bd2-bd4f-10f421907285",
    insurerSlug: "tongyang-life",
    insurerName: "동양생명",
    categoryLabel: "보험금청구서류",
    label: "실손보험금청구서 및 동의서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/dongyang/indemnity-health-insurance-claim-form-and-consent-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/dongyang/indemnity-health-insurance-claim-form-and-consent-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-lina-life-63d48fee-b92b-4b3f-86d3-d34e659185c4",
    insurerSlug: "lina-life",
    insurerName: "라이나생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구 및 수령위임장",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/lina/claim-and-receipt-power-of-attorney.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/lina/claim-and-receipt-power-of-attorney.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-lina-life-b6b1681e-9c2a-4406-b51d-d450dadc1340",
    insurerSlug: "lina-life",
    insurerName: "라이나생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/lina/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/lina/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-lina-general-21e72990-fd35-4dd5-aac1-e88db122fb68",
    insurerSlug: "lina-general",
    insurerName: "라이나손보",
    categoryLabel: "인보험",
    label: "보험금청구서(인보험)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lina/personal/claim-form-personal.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lina/personal/claim-form-personal.pdf",
    displayOrder: 150,
  },
  {
    id: "bohumschool-lina-general-3744f1b3-aa8e-4b51-92e4-086b0a8e2b94",
    insurerSlug: "lina-general",
    insurerName: "라이나손보",
    categoryLabel: "재물/배상책임",
    label: "보험금청구서(재물/배상책임)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lina/property/claim-form-property.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lina/property/claim-form-property.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-lina-general-c867744d-5f28-49fd-be4c-e9d55699e84c",
    insurerSlug: "lina-general",
    insurerName: "라이나손보",
    categoryLabel: "치아",
    label: "보험금청구서(보존)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lina/dental/claim-form-conservative.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lina/dental/claim-form-conservative.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-lina-general-d338cbc3-e13c-4c27-9ac7-2dd73590b743",
    insurerSlug: "lina-general",
    insurerName: "라이나손보",
    categoryLabel: "치아",
    label: "보험금청구서(보철)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lina/dental/claim-form-prosthetic.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lina/dental/claim-form-prosthetic.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-lina-general-007be6f2-4d88-4e2c-9e1c-d4492e14ab87",
    insurerSlug: "lina-general",
    insurerName: "라이나손보",
    categoryLabel: "펫보험",
    label: "보험금청구서(펫보험)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lina/pet/claim-form-pet.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lina/pet/claim-form-pet.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-lina-general-571135ab-9df4-445f-8433-ee240f72cdd1",
    insurerSlug: "lina-general",
    insurerName: "라이나손보",
    categoryLabel: "구매물품보상",
    label: "보험금청구서(구매물품보상)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lina/purchased-item/claim-form-purchased-item.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lina/purchased-item/claim-form-purchased-item.pdf",
    displayOrder: 450,
  },
  {
    id: "bohumschool-lotte-fire-de3711a0-3700-475d-96a9-928c274811bb",
    insurerSlug: "lotte-fire",
    insurerName: "롯데손해보험",
    categoryLabel: "일반상해/질병",
    label: "보험금청구서(일반상해/질병)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lotte/illness/claim-form-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lotte/illness/claim-form-illness.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-lotte-fire-c3e2d1be-3b25-4832-8e39-69c31a5b6161",
    insurerSlug: "lotte-fire",
    insurerName: "롯데손해보험",
    categoryLabel: "단체보험",
    label: "보험금청구서(단체보험용)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lotte/group/claim-form-group.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lotte/group/claim-form-group.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-lotte-fire-17d6e990-8bc5-43f1-aad2-72b19d7074ea",
    insurerSlug: "lotte-fire",
    insurerName: "롯데손해보험",
    categoryLabel: "교통사고",
    label: "보험금청구서(교통사고)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lotte/car-accident/claim-form-car-accident.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lotte/car-accident/claim-form-car-accident.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-lotte-fire-159589f7-9190-4797-8aa7-4e65453d01e5",
    insurerSlug: "lotte-fire",
    insurerName: "롯데손해보험",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lotte/car/claim-form-car.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lotte/car/claim-form-car.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-lotte-fire-2d041773-4f05-44c6-b130-0975db18336c",
    insurerSlug: "lotte-fire",
    insurerName: "롯데손해보험",
    categoryLabel: "재물/배상책임",
    label: "보험금청구서(재물/배상책임)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lotte/property/claim-form-property.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lotte/property/claim-form-property.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-lotte-fire-c91aa209-6054-4908-ae19-c2ebdd531576",
    insurerSlug: "lotte-fire",
    insurerName: "롯데손해보험",
    categoryLabel: "치아보험",
    label: "보험금청구서(치아보험)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lotte/dental/claim-form-dental.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lotte/dental/claim-form-dental.pdf",
    displayOrder: 600,
  },
  {
    id: "bohumschool-lotte-fire-ba5a69aa-a38f-4ff2-9976-61a64587bb22",
    insurerSlug: "lotte-fire",
    insurerName: "롯데손해보험",
    categoryLabel: "여행자",
    label: "보험금청구서(여행자)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lotte/travel/claim-form-travel.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lotte/travel/claim-form-travel.pdf",
    displayOrder: 700,
  },
  {
    id: "bohumschool-lotte-fire-65d0bc35-da3f-4c4e-8470-24b3a1b90c2a",
    insurerSlug: "lotte-fire",
    insurerName: "롯데손해보험",
    categoryLabel: "파손/EW",
    label: "보험금청구서(전자랜드 생활파워케어)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lotte/ew/claim-form-jeonjaland.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lotte/ew/claim-form-jeonjaland.pdf",
    displayOrder: 800,
  },
  {
    id: "bohumschool-lotte-fire-a88c6947-5c88-47f2-acee-c5c58fdcefe9",
    insurerSlug: "lotte-fire",
    insurerName: "롯데손해보험",
    categoryLabel: "파손/EW",
    label: "보험금청구서(쿠팡안심케어)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lotte/ew/claim-form-coupang.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lotte/ew/claim-form-coupang.pdf",
    displayOrder: 800,
  },
  {
    id: "bohumschool-lotte-fire-d35edace-bc75-431a-8e4e-e592b70fc01e",
    insurerSlug: "lotte-fire",
    insurerName: "롯데손해보험",
    categoryLabel: "파손/EW",
    label: "보험금청구서(하이마트)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/lotte/ew/claim-form-himart.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/lotte/ew/claim-form-himart.pdf",
    displayOrder: 800,
  },
  {
    id: "bohumschool-meritz-fire-4eb93169-470b-4e10-8353-80ef026563d0",
    insurerSlug: "meritz-fire",
    insurerName: "메리츠화재",
    categoryLabel: "질병",
    label: "보험금청구서(질병)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/meritz/illness/claim-form-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/meritz/illness/claim-form-illness.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-meritz-fire-aedf19da-ce95-4cc7-8f24-a3483821ba4a",
    insurerSlug: "meritz-fire",
    insurerName: "메리츠화재",
    categoryLabel: "상해사고",
    label: "보험금청구서(상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/meritz/damage/claim-form-damage.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/meritz/damage/claim-form-damage.pdf",
    displayOrder: 150,
  },
  {
    id: "bohumschool-meritz-fire-94271e24-984c-4800-bbf9-998c9839e56c",
    insurerSlug: "meritz-fire",
    insurerName: "메리츠화재",
    categoryLabel: "배상책임",
    label: "보험금청구서(배상책임)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/meritz/compensation/claim-form-compensation.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/meritz/compensation/claim-form-compensation.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-meritz-fire-5fa558ea-15d4-4968-84d4-364f03d0ac0a",
    insurerSlug: "meritz-fire",
    insurerName: "메리츠화재",
    categoryLabel: "재물사고",
    label: "보험금청구서(재물사고)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/meritz/property/claim-form-property.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/meritz/property/claim-form-property.pdf",
    displayOrder: 250,
  },
  {
    id: "bohumschool-meritz-fire-e7692389-07f3-4420-a34e-16d82e84cc11",
    insurerSlug: "meritz-fire",
    insurerName: "메리츠화재",
    categoryLabel: "자동차",
    label: "교통사고처리협조요청및보험금지급청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/meritz/car/claim-form-car.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/meritz/car/claim-form-car.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-meritz-fire-7f85f47e-491a-4d51-9266-3639f461144d",
    insurerSlug: "meritz-fire",
    insurerName: "메리츠화재",
    categoryLabel: "교통사고",
    label: "보험금청구서(교통사고)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/meritz/car-accident/claim-form-car-accident.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/meritz/car-accident/claim-form-car-accident.pdf",
    displayOrder: 350,
  },
  {
    id: "bohumschool-meritz-fire-706f6e73-27ea-4175-a94a-3047a652b423",
    insurerSlug: "meritz-fire",
    insurerName: "메리츠화재",
    categoryLabel: "치아",
    label: "보험금청구서(치아)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/meritz/dental/claim-form-dental.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/meritz/dental/claim-form-dental.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-meritz-fire-1551ece2-6955-471f-bb93-ff31f6b3ff25",
    insurerSlug: "meritz-fire",
    insurerName: "메리츠화재",
    categoryLabel: "펫",
    label: "보험금청구서(펫보험공통)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/meritz/pet/claim-form-pet-common.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/meritz/pet/claim-form-pet-common.pdf",
    displayOrder: 450,
  },
  {
    id: "bohumschool-meritz-fire-53a68a9d-07e2-4541-be0b-f0c2cc98843e",
    insurerSlug: "meritz-fire",
    insurerName: "메리츠화재",
    categoryLabel: "펫",
    label: "보험금청구서(펫보험배상책임)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/meritz/pet/claim-form-pet-compensation.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/meritz/pet/claim-form-pet-compensation.pdf",
    displayOrder: 450,
  },
  {
    id: "bohumschool-metlife-800d42ba-418b-40f6-a66b-3549836850a8",
    insurerSlug: "metlife",
    insurerName: "메트라이프",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서_일반",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/metlife/general-insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/metlife/general-insurance-claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-metlife-aa0e5895-19cf-43e5-9764-f4545ab96ff6",
    insurerSlug: "metlife",
    insurerName: "메트라이프",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서_큰글자",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/metlife/large-print-insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/metlife/large-print-insurance-claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-miraeasset-life-8efcc784-73fd-4b31-a62a-996f1e868443",
    insurerSlug: "miraeasset-life",
    insurerName: "미래에셋생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서류",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/miraeasset/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/miraeasset/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-miraeasset-life-f41b99d5-040b-4ea5-8078-2c2b8a153d7e",
    insurerSlug: "miraeasset-life",
    insurerName: "미래에셋생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서류(큰글)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/miraeasset/claim-form-big.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/miraeasset/claim-form-big.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-samsung-life-d35cd8ab-e8e3-4d8a-935c-6a150fbe140e",
    insurerSlug: "samsung-life",
    insurerName: "삼성생명",
    categoryLabel: "공통",
    label: "보험금청구서(개인)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/samsung/common/claim-form--individual-.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/samsung/common/claim-form-(individual).pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-samsung-life-93cbc65d-4846-457f-b2a3-9d8fb8e38cfc",
    insurerSlug: "samsung-life",
    insurerName: "삼성생명",
    categoryLabel: "공통",
    label: "보험금청구서(법인단체수익자용)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/samsung/common/claim-form--corporate-.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/samsung/common/claim-form-(corporate).pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-samsung-life-fee6c418-f3f2-4fa0-b2b1-e72af67175ae",
    insurerSlug: "samsung-life",
    insurerName: "삼성생명",
    categoryLabel: "공통",
    label: "위임장",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/samsung/common/power-of-attorney.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/samsung/common/power-of-attorney.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-samsung-fire-c6ad8e85-e41a-490a-872d-548acb3965cb",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "질병/상해",
    label: "보험금청구서(질병/상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/illness/claim-form-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/illness/claim-form-illness.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-samsung-fire-643c5ef1-0ff7-49a0-8929-4f779e9a2769",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "배상",
    label: "보험금청구서(배상, 가족용)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/compensation/claim-form-compensation-family.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/compensation/claim-form-compensation-family.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-samsung-fire-7a2df5b1-2732-4bad-b82c-4efc46a37780",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "배상",
    label: "보험금청구서(배상)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/compensation/claim-form-compensation.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/compensation/claim-form-compensation.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-samsung-fire-5e24b820-209c-4ea4-a35c-69039a2b7869",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "화재",
    label: "보험금청구서(화재)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/fire/claim-form-fire.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/fire/claim-form-fire.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-samsung-fire-4387b6e0-0b36-496c-8219-c5069bcc9d31",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "치아 질병/상해",
    label: "보험금청구서(치아 질병/상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/dental/claim-form-dental.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/dental/claim-form-dental.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-samsung-fire-c626543e-a9f7-4e59-a986-a94731e09fa6",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차, 가해자불명)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/car/claim-form-car-unknown.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/car/claim-form-car-unknown.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-samsung-fire-fdb9139f-b4a7-4316-9614-67c78f52a78d",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/car/claim-form-car.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/car/claim-form-car.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-samsung-fire-a6681cd8-1828-480d-94fd-e7b78e65b4fc",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "교통상해",
    label: "보험금청구서(교통상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/traffic-accident/claim-form-traffic-accident.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/traffic-accident/claim-form-traffic-accident.pdf",
    displayOrder: 600,
  },
  {
    id: "bohumschool-samsung-fire-e4a4c64d-fb6e-4ceb-ae71-3519a1e52dfb",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "가전제품",
    label: "보험금청구서(가전제품)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/home-appliances/claim-form-home-appliances.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/home-appliances/claim-form-home-appliances.pdf",
    displayOrder: 700,
  },
  {
    id: "bohumschool-samsung-fire-5b5b2171-c053-4db9-a7e8-624b84ec192b",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "도난",
    label: "보험금청구서(도난)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/theft/claim-form-theft.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/theft/claim-form-theft.pdf",
    displayOrder: 800,
  },
  {
    id: "bohumschool-samsung-fire-274f6308-f2b5-443f-88c7-89d3b0307683",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "반려동물",
    label: "보험금청구서(반려동물 배상책임)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/pet/claim-form-pet-compensation.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/pet/claim-form-pet-compensation.pdf",
    displayOrder: 900,
  },
  {
    id: "bohumschool-samsung-fire-cb776dc2-6e37-4a23-8f4b-0a2101f2acbf",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "반려동물",
    label: "보험금청구서(반려동물 질병/상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/pet/claim-form-pet-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/pet/claim-form-pet-illness.pdf",
    displayOrder: 900,
  },
  {
    id: "bohumschool-samsung-fire-3d3b1ea2-ca98-4123-84bc-d5ea098e95d0",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "여행",
    label: "보험금청구서(여행)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/travel/claim-form-traver.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/travel/claim-form-traver.pdf",
    displayOrder: 1000,
  },
  {
    id: "bohumschool-samsung-fire-93d19d92-66b6-4776-aacb-a8bfb1befe9e",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "여행 중 질병/상해",
    label: "보험금청구서(여행 중 질병/상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/travel-illness/claim-form-travel-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/travel-illness/claim-form-travel-illness.pdf",
    displayOrder: 1100,
  },
  {
    id: "bohumschool-samsung-fire-c91c810e-0462-4d7b-9eb6-63e2dfb469fe",
    insurerSlug: "samsung-fire",
    insurerName: "삼성화재",
    categoryLabel: "홀인원/알바트로스",
    label: "보험금청구서(홀인원/알바트로스)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/hole-in-one/claim-form-hole-in-one.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/hole-in-one/claim-form-hole-in-one.pdf",
    displayOrder: 1200,
  },
  {
    id: "bohumschool-samsung-digital-8115b2ec-3f11-44d4-9a28-535180c57731",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "질병/상해",
    label: "보험금청구서(질병/상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/illness/claim-form-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/illness/claim-form-illness.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-samsung-digital-ada66f35-fe55-40f7-9609-0f0d8104887f",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "배상",
    label: "보험금청구서(배상, 가족용)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/compensation/claim-form-compensation-family.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/compensation/claim-form-compensation-family.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-samsung-digital-9f94f370-d9e5-4803-ab17-1c7fd8d0a51f",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "배상",
    label: "보험금청구서(배상)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/compensation/claim-form-compensation.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/compensation/claim-form-compensation.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-samsung-digital-ea0ceecf-cb25-409f-a264-a5142943a440",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "화재",
    label: "보험금청구서(화재)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/fire/claim-form-fire.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/fire/claim-form-fire.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-samsung-digital-7ce1888c-6f15-453c-9477-d18c1896b402",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "치아 질병/상해",
    label: "보험금청구서(치아 질병/상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/dental/claim-form-dental.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/dental/claim-form-dental.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-samsung-digital-2b30a844-7d46-4fe6-a790-e459b9f84213",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차, 가해자불명)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/car/claim-form-car-unknown.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/car/claim-form-car-unknown.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-samsung-digital-d2ea7dd2-f2a9-49d4-875e-9352770a4efb",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/car/claim-form-car.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/car/claim-form-car.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-samsung-digital-483fd4c8-3fdf-42ed-aba8-9d847436e674",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "교통상해",
    label: "보험금청구서(교통상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/traffic-accident/claim-form-traffic-accident.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/traffic-accident/claim-form-traffic-accident.pdf",
    displayOrder: 600,
  },
  {
    id: "bohumschool-samsung-digital-3d7620cd-e716-4957-8b2e-fbb8b333edd4",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "가전제품",
    label: "보험금청구서(가전제품)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/home-appliances/claim-form-home-appliances.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/home-appliances/claim-form-home-appliances.pdf",
    displayOrder: 700,
  },
  {
    id: "bohumschool-samsung-digital-5c74b613-a9a2-40d0-8b6a-c4b502553c78",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "도난",
    label: "보험금청구서(도난)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/theft/claim-form-theft.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/theft/claim-form-theft.pdf",
    displayOrder: 800,
  },
  {
    id: "bohumschool-samsung-digital-23f82ab6-6946-4751-a2ac-594f591842a5",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "반려동물",
    label: "보험금청구서(반려동물 배상책임)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/pet/claim-form-pet-compensation.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/pet/claim-form-pet-compensation.pdf",
    displayOrder: 900,
  },
  {
    id: "bohumschool-samsung-digital-fb8a7c4e-d069-461a-aeef-6e9f29388e22",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "반려동물",
    label: "보험금청구서(반려동물 질병/상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/pet/claim-form-pet-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/pet/claim-form-pet-illness.pdf",
    displayOrder: 900,
  },
  {
    id: "bohumschool-samsung-digital-2271fec7-d693-4e11-8d0f-152f2839e5f9",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "여행",
    label: "보험금청구서(여행)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/travel/claim-form-traver.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/travel/claim-form-traver.pdf",
    displayOrder: 1000,
  },
  {
    id: "bohumschool-samsung-digital-62188003-6a42-468a-bda7-734de9424766",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "여행 중 질병/상해",
    label: "보험금청구서(여행 중 질병/상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/travel-illness/claim-form-travel-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/travel-illness/claim-form-travel-illness.pdf",
    displayOrder: 1100,
  },
  {
    id: "bohumschool-samsung-digital-a589c20e-eff8-4b0d-9ba6-348ab93fdf3a",
    insurerSlug: "samsung-digital",
    insurerName: "삼성화재다이렉트착",
    categoryLabel: "홀인원/알바트로스",
    label: "보험금청구서(홀인원/알바트로스)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/samsung/hole-in-one/claim-form-hole-in-one.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/samsung/hole-in-one/claim-form-hole-in-one.pdf",
    displayOrder: 1200,
  },
  {
    id: "bohumschool-suhyeop-mutual-e3f65a67-5778-4206-a048-9b972c7bf347",
    insurerSlug: "suhyeop-mutual",
    insurerName: "수협공제",
    categoryLabel: "질병/상해",
    label: "공제금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/suhyup/illnesss/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/suhyup/illnesss/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-suhyeop-mutual-6f827793-48ae-49e6-9339-f3345bdb989d",
    insurerSlug: "suhyeop-mutual",
    insurerName: "수협공제",
    categoryLabel: "배상책임",
    label: "공제금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/suhyup/compensation/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/suhyup/compensation/claim-form.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-suhyeop-mutual-6c321e2f-a65c-42fe-a89f-dd63a277fd90",
    insurerSlug: "suhyeop-mutual",
    insurerName: "수협공제",
    categoryLabel: "재물",
    label: "공제금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/suhyup/property/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/suhyup/property/claim-form.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-shinhan-life-3afb5d01-a8e0-432a-90b8-1c11cccf2f73",
    insurerSlug: "shinhan-life",
    insurerName: "신한라이프",
    categoryLabel: "공통",
    label: "보험금청구서 및 상세동의서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/shinhan/common/claim-form-and-detailed-consent-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/shinhan/common/claim-form-and-detailed-consent-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-shinhan-life-cc269860-1828-48c2-96f9-9a5dc7575125",
    insurerSlug: "shinhan-life",
    insurerName: "신한라이프",
    categoryLabel: "공통",
    label: "보험금청구서 및 상세동의서(글자크기확대)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/shinhan/common/claim-form-and-detailed-consent-form-big-font.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/shinhan/common/claim-form-and-detailed-consent-form-big-font.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-shinhanez-digital-6d06d72b-84e1-43f9-8a28-8661d144705e",
    insurerSlug: "shinhanez-digital",
    insurerName: "신한EZ손해보험",
    categoryLabel: "질병/상해",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/shinhan-ez/illness-injury/insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/shinhan-ez/illness-injury/insurance-claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-shinhanez-digital-6dca39bd-71f5-45d6-9709-2c081b3a4240",
    insurerSlug: "shinhanez-digital",
    insurerName: "신한EZ손해보험",
    categoryLabel: "교통/상해",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/shinhan-ez/traffic-injury/insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/shinhan-ez/traffic-injury/insurance-claim-form.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-shinhanez-digital-99d8f4fb-6f7a-4a12-bdbc-942efa81a042",
    insurerSlug: "shinhanez-digital",
    insurerName: "신한EZ손해보험",
    categoryLabel: "치아",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/shinhan-ez/dental/insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/shinhan-ez/dental/insurance-claim-form.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-shinhanez-digital-65c4a5a6-ea16-42a6-abee-e1f5668aa93b",
    insurerSlug: "shinhanez-digital",
    insurerName: "신한EZ손해보험",
    categoryLabel: "주택화재",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/shinhan-ez/home-fire/insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/shinhan-ez/home-fire/insurance-claim-form.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-shinhanez-digital-8a69bb35-3d78-48c1-a1c4-43a23dc0c5c6",
    insurerSlug: "shinhanez-digital",
    insurerName: "신한EZ손해보험",
    categoryLabel: "펫",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/shinhan-ez/pet/insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/shinhan-ez/pet/insurance-claim-form.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-shinhanez-digital-3d8eb72e-2371-4f4e-b463-377eb3426200",
    insurerSlug: "shinhanez-digital",
    insurerName: "신한EZ손해보험",
    categoryLabel: "펫",
    label: "펫보험청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/shinhan-ez/pet/pet-insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/shinhan-ez/pet/pet-insurance-claim-form.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-shinhanez-digital-c88bc79f-06e8-4b6c-85a8-7eb2b2a97b09",
    insurerSlug: "shinhanez-digital",
    insurerName: "신한EZ손해보험",
    categoryLabel: "여행",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/shinhan-ez/travel/insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/shinhan-ez/travel/insurance-claim-form.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-shinhanez-digital-70fa313b-4cae-470a-8108-51b760e9dd3b",
    insurerSlug: "shinhanez-digital",
    insurerName: "신한EZ손해보험",
    categoryLabel: "골프",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/shinhan-ez/golf/insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/shinhan-ez/golf/insurance-claim-form.pdf",
    displayOrder: 600,
  },
  {
    id: "bohumschool-shinhyeop-mutual-393b2f5c-1cb5-43c2-adcb-a356050a5bcd",
    insurerSlug: "shinhyeop-mutual",
    insurerName: "신협공제",
    categoryLabel: "공통",
    label: "공제금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/shinhyup/common/claim-form.pdf.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/shinhyup/common/claim-form.pdf.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-yebyeol-insurance-0486f44d-094f-4dd2-a707-0ec085d7eca4",
    insurerSlug: "yebyeol-insurance",
    insurerName: "예별손해보험",
    categoryLabel: "교통상해",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/yebeol/traffic-accident/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/yebeol/traffic-accident/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-yebyeol-insurance-609f2514-435b-4eb9-9086-c6c0e9ee4653",
    insurerSlug: "yebyeol-insurance",
    insurerName: "예별손해보험",
    categoryLabel: "질병/상해",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/yebeol/illness/claim-form-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/yebeol/illness/claim-form-illness.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-yebyeol-insurance-ab251a04-b4dd-4c2d-9cbe-94939934b4cf",
    insurerSlug: "yebyeol-insurance",
    insurerName: "예별손해보험",
    categoryLabel: "재물/배상책임",
    label: "보험금청구서(재물보험)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/yebeol/property/claim-form-property.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/yebeol/property/claim-form-property.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-yebyeol-insurance-54a05baf-4c94-4e9c-975c-f702965e0470",
    insurerSlug: "yebyeol-insurance",
    insurerName: "예별손해보험",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차,대물배상)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/yebeol/car/claim-form-car-property.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/yebeol/car/claim-form-car-property.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-yebyeol-insurance-0a51bf4f-4cf6-43d6-89f9-ea0f289779cd",
    insurerSlug: "yebyeol-insurance",
    insurerName: "예별손해보험",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차,대인배상)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/yebeol/car/claim-form-car-injury.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/yebeol/car/claim-form-car-injury.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-yebyeol-insurance-64b418f0-9d34-408f-b294-6cd94f21c185",
    insurerSlug: "yebyeol-insurance",
    insurerName: "예별손해보험",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차,무보험차상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/yebeol/car/claim-form-car-no-insurance.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/yebeol/car/claim-form-car-no-insurance.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-yebyeol-insurance-11aefd2d-37c9-4772-a8e1-86bc77844c6e",
    insurerSlug: "yebyeol-insurance",
    insurerName: "예별손해보험",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차,자기신체사고/자동차상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/yebeol/car/claim-form-car-injury-mine.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/yebeol/car/claim-form-car-injury-mine.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-yebyeol-insurance-3ed041f6-b250-484c-b13b-ec95c84ee359",
    insurerSlug: "yebyeol-insurance",
    insurerName: "예별손해보험",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차,자기차량)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/yebeol/car/claim-form-car-mine.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/yebeol/car/claim-form-car-mine.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-yebyeol-insurance-be4580b4-b34c-40b7-a290-7c0825287558",
    insurerSlug: "yebyeol-insurance",
    insurerName: "예별손해보험",
    categoryLabel: "치아",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/yebeol/dental/claim-form-dental.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/yebeol/dental/claim-form-dental.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-woochegook-mutual-43758de8-4d29-4e7d-8f75-477528555c30",
    insurerSlug: "woochegook-mutual",
    insurerName: "우체국보험",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/postoffice/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/postoffice/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-woochegook-mutual-e83beb51-e8b8-4394-a12c-2e59837d3b98",
    insurerSlug: "woochegook-mutual",
    insurerName: "우체국보험",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서(단체전용보험)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/postoffice/claim-form-corporate.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/postoffice/claim-form-corporate.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-chubb-life-ee040f4f-4017-4020-90ab-de454237f073",
    insurerSlug: "chubb-life",
    insurerName: "처브라이프생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/chubb/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/chubb/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-chubb-life-be9dcbf7-f353-4baf-9d39-0f0c9f46349e",
    insurerSlug: "chubb-life",
    insurerName: "처브라이프생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서(덴탈케어보험)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/chubb/claim-form-dental.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/chubb/claim-form-dental.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-kakaopay-digital-9ccb62ad-7427-47be-8f77-c1fe52ed6afc",
    insurerSlug: "kakaopay-digital",
    insurerName: "카카오페이손해보험",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서(상해질병)",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/kakaopay/claim-form-for-injury-and-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/kakaopay/claim-form-for-injury-and-illness.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-kakaopay-digital-a381bd69-08a1-40da-b843-ec528f9d5a2b",
    insurerSlug: "kakaopay-digital",
    insurerName: "카카오페이손해보험",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서(재물배상)",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/kakaopay/claim-form-for-property-and-liability.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/kakaopay/claim-form-for-property-and-liability.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-carrot-digital-5d3b5e95-8585-4782-8393-240873d4f4e5",
    insurerSlug: "carrot-digital",
    insurerName: "캐롯손해보험",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/carrot/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/carrot/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-fubonhyundai-life-8bc90c4a-822f-4739-a67a-3681bfc5977a",
    insurerSlug: "fubonhyundai-life",
    insurerName: "푸본현대생명",
    categoryLabel: "보험금청구서류",
    label: "사고보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/fubon/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/fubon/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hana-life-e0713faf-39e8-4c62-81aa-ae99f96968d2",
    insurerSlug: "hana-life",
    insurerName: "하나생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서(개인)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/hana/claim-form-personal.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/hana/claim-form-personal.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hana-life-0f5f1620-6251-4bb4-b8aa-6e845751b0bb",
    insurerSlug: "hana-life",
    insurerName: "하나생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서(법인)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/hana/claim-form-corporate.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/hana/claim-form-corporate.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hana-general-5f43469b-f1e1-4b27-a1fc-c6e584c7347b",
    insurerSlug: "hana-general",
    insurerName: "하나손해보험",
    categoryLabel: "질병",
    label: "보험금청구서(질병)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hana/illness/claim-form-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hana/illness/claim-form-illness.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hana-general-a7b4074b-3dcc-40dd-9b1f-8ba71c21b961",
    insurerSlug: "hana-general",
    insurerName: "하나손해보험",
    categoryLabel: "상해",
    label: "보험금청구서(상해/질병)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hana/damage/claim-form-damage.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hana/damage/claim-form-damage.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-hana-general-e4b98a43-7c33-4a99-97e5-2491ce52c478",
    insurerSlug: "hana-general",
    insurerName: "하나손해보험",
    categoryLabel: "교통",
    label: "보험금청구서(교통)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hana/traffic/claim-form-traffic.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hana/traffic/claim-form-traffic.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-hana-general-d62b13f7-686d-4dc0-9d94-1bf211b4eaef",
    insurerSlug: "hana-general",
    insurerName: "하나손해보험",
    categoryLabel: "치과",
    label: "보험금청구서(치과)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hana/dental/claim-form-dental.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hana/dental/claim-form-dental.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-hana-general-c067aa4e-4651-4846-bb81-ee5019ff1fa5",
    insurerSlug: "hana-general",
    insurerName: "하나손해보험",
    categoryLabel: "여행자보험",
    label: "보험금청구서(여행자,상해/질병)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hana/travel/claim-form-travel-illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hana/travel/claim-form-travel-illness.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-hana-general-6d7aeaf9-e49e-4089-9892-d3d284d560b3",
    insurerSlug: "hana-general",
    insurerName: "하나손해보험",
    categoryLabel: "여행자보험",
    label: "보험금청구서(여행자,재물/배책)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hana/travel/claim-form-travel-property.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hana/travel/claim-form-travel-property.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-hana-general-1439bdf8-4625-4414-966c-2d91b6999cfd",
    insurerSlug: "hana-general",
    insurerName: "하나손해보험",
    categoryLabel: "시(구)민안전보험",
    label: "보험금청구서(시민안전보험)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hana/citizen/claim-form-citizen.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hana/citizen/claim-form-citizen.pdf",
    displayOrder: 600,
  },
  {
    id: "bohumschool-hana-general-84c67b61-6238-4325-bd56-037265db1ea9",
    insurerSlug: "hana-general",
    insurerName: "하나손해보험",
    categoryLabel: "교직원안심",
    label: "보험금청구서(교직원안심)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hana/school-employee/claim-form-teacher.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hana/school-employee/claim-form-teacher.pdf",
    displayOrder: 700,
  },
  {
    id: "bohumschool-hanaoneday-digital-5c48a494-220a-46c8-92ab-6385368f1b4e",
    insurerSlug: "hanaoneday-digital",
    insurerName: "하나원데이보험",
    categoryLabel: "일반보험",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/hana-oneday/common/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/hana-oneday/common/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hanaoneday-digital-a189d516-2d76-4d67-b9dd-96b72d48f1ac",
    insurerSlug: "hanaoneday-digital",
    insurerName: "하나원데이보험",
    categoryLabel: "자동차사고",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/digital_insurance/hana-oneday/car/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/digital_insurance/hana-oneday/car/claim-form.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-hanwha-life-96ac0096-6c36-42b8-92f3-7da3b2d0190e",
    insurerSlug: "hanwha-life",
    insurerName: "한화생명",
    categoryLabel: "공통",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/hanhwa/common/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/hanhwa/common/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hanwha-general-90a62728-0844-4d11-944e-0ceca26c16f2",
    insurerSlug: "hanwha-general",
    insurerName: "한화손해보험",
    categoryLabel: "장기/일반/연금보험",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hanhwa/common/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hanhwa/common/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hanwha-general-ffa5f40b-7550-455d-aa5a-adc9c2ee743f",
    insurerSlug: "hanwha-general",
    insurerName: "한화손해보험",
    categoryLabel: "장기/일반/연금보험",
    label: "보험금청구서(국방부 단체상해보험)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hanhwa/common/claim-form-corporate.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hanhwa/common/claim-form-corporate.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hanwha-general-c7f9c8a3-5ccc-4cdc-ae23-3b0768f432b5",
    insurerSlug: "hanwha-general",
    insurerName: "한화손해보험",
    categoryLabel: "장기/일반/연금보험",
    label: "보험금청구서(반려동물)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hanhwa/common/claim-form-pet.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hanhwa/common/claim-form-pet.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hyundai-marine-08e7a85c-f692-4daa-af67-4ddb3fb23586",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "질병/일반상해",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/illness/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/illness/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hyundai-marine-7de3c1c4-01b3-40b0-b6c9-9e3c2e14a704",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "질병/일반상해",
    label: "보험금청구서(단체)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/illness/claim-form-corporate.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/illness/claim-form-corporate.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hyundai-marine-d53acb75-fb9b-40fb-8410-9904ad0fe121",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "질병/일반상해",
    label: "보험금청구서(치아)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/illness/claim-form-dental.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/illness/claim-form-dental.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hyundai-marine-db922231-6186-45b1-a7ed-305b56957ab0",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "질병/일반상해",
    label: "보험금청구서(큰글씨)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/illness/claim-form-big-font.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/illness/claim-form-big-font.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-hyundai-marine-16092808-6aaf-4b4e-8b62-07eea1181ce7",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "교통상해",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/traffic-damage/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/traffic-damage/claim-form.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-hyundai-marine-4e6cbf6b-2014-4b95-a5c8-9f3a571cbecb",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "교통상해",
    label: "보험금청구서(큰글씨)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/traffic-damage/claim-form-big-font.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/traffic-damage/claim-form-big-font.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-hyundai-marine-bdab38e6-a585-4d7f-aa13-39baf07398b5",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "배상책임",
    label: "보험금청구서(배상책임,가족용)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/compensation/claim-form-compensation-family.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/compensation/claim-form-compensation-family.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-hyundai-marine-b3e00257-dffe-4a02-846b-c46014ab7e29",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "배상책임",
    label: "보험금청구서(배상책임)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/compensation/claim-form-compensation.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/compensation/claim-form-compensation.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-hyundai-marine-3e970b29-6cab-4090-b69a-a75a048b6c3b",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "배상책임",
    label: "보험금청구서(의사배상책임)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/compensation/claim-form-compensation-doctor.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/compensation/claim-form-compensation-doctor.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-hyundai-marine-9568e6dd-fda3-4306-a53d-97e88e0e4561",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "재물",
    label: "보험금청구서(재물)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/property/claim-form-property.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/property/claim-form-property.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-hyundai-marine-29bd9cb0-bd04-4829-ba05-12c0fe875115",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/car/claim-form-car.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/car/claim-form-car.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-hyundai-marine-8ca9621d-eb0c-4819-ace4-a69713e0ddbe",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "여행",
    label: "보험금청구서(도난/파손)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/travel/claim-form-theft.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/travel/claim-form-theft.pdf",
    displayOrder: 600,
  },
  {
    id: "bohumschool-hyundai-marine-29f29064-af20-4be8-9c81-abe586cc26d3",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "여행",
    label: "보험금청구서(배상)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/travel/claim-form-compensation.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/travel/claim-form-compensation.pdf",
    displayOrder: 600,
  },
  {
    id: "bohumschool-hyundai-marine-dcc50b29-6960-4755-8c92-e69b3d419586",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "여행",
    label: "보험금청구서(여행)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/travel/claim-form-travel.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/travel/claim-form-travel.pdf",
    displayOrder: 600,
  },
  {
    id: "bohumschool-hyundai-marine-a3729189-2a4c-4c59-8069-807ceca47f59",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "펫보험",
    label: "보험금청구서(펫보험,배상책임)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/pet/claim-form-pet-compensation.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/pet/claim-form-pet-compensation.pdf",
    displayOrder: 700,
  },
  {
    id: "bohumschool-hyundai-marine-7f1ce722-754e-445d-9120-dfea5074cee8",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "펫보험",
    label: "보험금청구서(펫보험,의료비/장례비)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/pet/claim-form-pet.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/pet/claim-form-pet.pdf",
    displayOrder: 700,
  },
  {
    id: "bohumschool-hyundai-marine-6b2c307c-4eb8-40e3-99b7-535b8f2d3bda",
    insurerSlug: "hyundai-marine",
    insurerName: "현대해상",
    categoryLabel: "기타",
    label: "보험금청구서(홀인원)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/hyundai/etc/claim-form-hole-in-one.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/hyundai/etc/claim-form-hole-in-one.pdf",
    displayOrder: 800,
  },
  {
    id: "bohumschool-heungkuk-life-61104b07-59b9-448b-b370-ca8f60a35693",
    insurerSlug: "heungkuk-life",
    insurerName: "흥국생명",
    categoryLabel: "공통",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/heungkuk/common/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/heungkuk/common/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-heungkuk-fire-9c856e94-2a15-4d59-a01c-2c4fa68b4c73",
    insurerSlug: "heungkuk-fire",
    insurerName: "흥국화재",
    categoryLabel: "질병상해",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/heungkuk/illness/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/heungkuk/illness/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-heungkuk-fire-603b4b97-10d4-41b2-8061-50f65f06b7e9",
    insurerSlug: "heungkuk-fire",
    insurerName: "흥국화재",
    categoryLabel: "교통상해",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/heungkuk/traffic-damage/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/heungkuk/traffic-damage/claim-form.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-heungkuk-fire-aa93951f-d652-4516-b434-c81c942a1aad",
    insurerSlug: "heungkuk-fire",
    insurerName: "흥국화재",
    categoryLabel: "배상책임",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/heungkuk/compensation/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/heungkuk/compensation/claim-form.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-heungkuk-fire-c293a828-e5d6-47b8-bfdd-1195d920d072",
    insurerSlug: "heungkuk-fire",
    insurerName: "흥국화재",
    categoryLabel: "화재/도난",
    label: "보험금청구서(도난)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/heungkuk/fire-theft/claim-form-theft.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/heungkuk/fire-theft/claim-form-theft.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-heungkuk-fire-d6c900f5-113d-4345-97d2-e3900bf1a31e",
    insurerSlug: "heungkuk-fire",
    insurerName: "흥국화재",
    categoryLabel: "화재/도난",
    label: "보험금청구서(화재)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/heungkuk/fire-theft/claim-form-fire.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/heungkuk/fire-theft/claim-form-fire.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-heungkuk-fire-97a4a255-544a-477c-8087-19abbb056856",
    insurerSlug: "heungkuk-fire",
    insurerName: "흥국화재",
    categoryLabel: "치아보험",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/heungkuk/dental/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/heungkuk/dental/claim-form.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-heungkuk-fire-9108dfa5-93fa-4589-bf48-4386691c551f",
    insurerSlug: "heungkuk-fire",
    insurerName: "흥국화재",
    categoryLabel: "자동차",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/heungkuk/car/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/heungkuk/car/claim-form.pdf",
    displayOrder: 600,
  },
  {
    id: "bohumschool-heungkuk-fire-e6c3ce3a-d58c-457d-9821-629a62861d82",
    insurerSlug: "heungkuk-fire",
    insurerName: "흥국화재",
    categoryLabel: "여행자보험",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/heungkuk/travel/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/heungkuk/travel/claim-form.pdf",
    displayOrder: 700,
  },
  {
    id: "bohumschool-heungkuk-fire-9d20f02f-d535-4458-b5c5-c7b8debae948",
    insurerSlug: "heungkuk-fire",
    insurerName: "흥국화재",
    categoryLabel: "골프보험",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/heungkuk/golf/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/heungkuk/golf/claim-form.pdf",
    displayOrder: 800,
  },
  {
    id: "bohumschool-abl-life-0bdbae5a-2ab2-4dd1-9941-0437245ffddb",
    insurerSlug: "abl-life",
    insurerName: "ABL생명",
    categoryLabel: "보험금청구서류",
    label: "사고보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/abl/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/abl/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-aia-life-fbacb324-fe5b-4c30-be63-64a84decff5f",
    insurerSlug: "aia-life",
    insurerName: "AIA생명",
    categoryLabel: "보험금청구서류",
    label: "보험금신청서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/aia/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/aia/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-aig-general-222146e0-3006-4f4f-a5a6-c4d40dba3729",
    insurerSlug: "aig-general",
    insurerName: "AIG손해보험",
    categoryLabel: "상해질병보험",
    label: "보험금신청서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/aig/injury-disease-insurance/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/aig/injury-disease-insurance/claim-form.PDF",
    displayOrder: 100,
  },
  {
    id: "bohumschool-aig-general-90223eba-6e3f-42ab-884e-573eb4921663",
    insurerSlug: "aig-general",
    insurerName: "AIG손해보험",
    categoryLabel: "개인배상책임보험",
    label: "보험금신청서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/aig/personal-liability-insurance/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/aig/personal-liability-insurance/claim-form.PDF",
    displayOrder: 200,
  },
  {
    id: "bohumschool-aig-general-b90615e6-d645-4b3f-b933-383df377a150",
    insurerSlug: "aig-general",
    insurerName: "AIG손해보험",
    categoryLabel: "개인재산보험",
    label: "보험금신청서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/aig/property-insurance/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/aig/property-insurance/claim-form.PDF",
    displayOrder: 300,
  },
  {
    id: "bohumschool-aig-general-f16ec4f4-70c7-4ec7-8754-8629335311b1",
    insurerSlug: "aig-general",
    insurerName: "AIG손해보험",
    categoryLabel: "여행자보험",
    label: "보험금신청서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/aig/travel-insurance/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/aig/travel-insurance/claim-form.PDF",
    displayOrder: 400,
  },
  {
    id: "bohumschool-aig-general-3dbb6889-e9ab-472e-aac8-f7d09056d4e7",
    insurerSlug: "aig-general",
    insurerName: "AIG손해보험",
    categoryLabel: "운전자보험",
    label: "보험금신청서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/aig/driver-insurance/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/aig/driver-insurance/claim-form.PDF",
    displayOrder: 500,
  },
  {
    id: "bohumschool-aig-general-595e4a0d-ac77-44b6-9bcf-eddf7d128eef",
    insurerSlug: "aig-general",
    insurerName: "AIG손해보험",
    categoryLabel: "치아보험",
    label: "보험금신청서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/aig/dental-insurance/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/aig/dental-insurance/claim-form.PDF",
    displayOrder: 600,
  },
  {
    id: "bohumschool-axa-insurance-b3b6669a-9162-4522-b5f3-68374ba310d1",
    insurerSlug: "axa-insurance",
    insurerName: "AXA손해보험",
    categoryLabel: "질병/상해",
    label: "보험금청구서(상해질병)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/axa/illness/claim_invoice_accident_illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/axa/illness/claim_invoice_accident_illness.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-axa-insurance-0df8df9e-7eea-48fc-9f6c-a95990fe3b08",
    insurerSlug: "axa-insurance",
    insurerName: "AXA손해보험",
    categoryLabel: "교통상해",
    label: "보험금청구서(교통상해)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/axa/traffic-accident/claim_invoice_accident_illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/axa/traffic-accident/claim_invoice_accident_illness.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-axa-insurance-e1bc52dd-2349-4d99-9239-85e512d41c32",
    insurerSlug: "axa-insurance",
    insurerName: "AXA손해보험",
    categoryLabel: "재물사고/배상책임",
    label: "보험금청구서(재물사고/배상책임)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/axa/property/claim_invoice_liability_otpa.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/axa/property/claim_invoice_liability_otpa.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-axa-insurance-8444494c-9988-4547-958c-29bc5c3540fb",
    insurerSlug: "axa-insurance",
    insurerName: "AXA손해보험",
    categoryLabel: "치아",
    label: "보험금청구서(치아)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/axa/dental/claim_invoice_accident_illness.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/axa/dental/claim_invoice_accident_illness.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-axa-insurance-0da5eb7b-a4a1-4aff-a3db-a7aa323b1623",
    insurerSlug: "axa-insurance",
    insurerName: "AXA손해보험",
    categoryLabel: "해외여행자",
    label: "보험금청구서(해외여행자)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/axa/travel/claim_invoice_liability_otpa.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/axa/travel/claim_invoice_liability_otpa.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-bnp-life-15e63b31-ca21-438e-ac4c-48e213c29a8f",
    insurerSlug: "bnp-life",
    insurerName: "BNP파리바카디프생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서 및 상세동의서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/bnp/claim-form-and-detailed-consent-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/bnp/claim-form-and-detailed-consent-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-bnp-life-c38ed51c-5811-49cb-bc41-40df23b93c1a",
    insurerSlug: "bnp-life",
    insurerName: "BNP파리바카디프생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서 및 상세동의서(단체용)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/bnp/claim-form-and-detailed-consent-form-corporate.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/bnp/claim-form-and-detailed-consent-form-corporate.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-db-life-af487f01-be9d-4bef-aa25-1648fe34913c",
    insurerSlug: "db-life",
    insurerName: "DB생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/db/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/db/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-db-insurance-5f2672ae-2564-4e4d-afd0-3c7a0d5654c1",
    insurerSlug: "db-insurance",
    insurerName: "DB손해보험",
    categoryLabel: "공통",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/db/common/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/db/common/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-db-insurance-62dc1571-0c47-4084-9d53-6b8d1c445b30",
    insurerSlug: "db-insurance",
    insurerName: "DB손해보험",
    categoryLabel: "공통",
    label: "보험금청구서(큰글씨)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/db/common/claim-form-big-font.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/db/common/claim-form-big-font.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-db-insurance-551b75bc-1f9e-4e09-bacc-efabb2ad115d",
    insurerSlug: "db-insurance",
    insurerName: "DB손해보험",
    categoryLabel: "여행자",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/db/travel/claim-form-travel.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/db/travel/claim-form-travel.pdf",
    displayOrder: 600,
  },
  {
    id: "bohumschool-db-insurance-6ec7480b-ef3e-40f8-8840-984e03ba099f",
    insurerSlug: "db-insurance",
    insurerName: "DB손해보험",
    categoryLabel: "재물/배상책임",
    label: "누수사고청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/db/fire/water-leak-accident-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/db/fire/water-leak-accident-claim-form.pdf",
    displayOrder: 700,
  },
  {
    id: "bohumschool-db-insurance-1cf48ecb-0492-4d06-bd9b-62076b8020a4",
    insurerSlug: "db-insurance",
    insurerName: "DB손해보험",
    categoryLabel: "펫보험",
    label: "보험금청구서(펫보험)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/db/pet/claim-form-pet.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/db/pet/claim-form-pet.pdf",
    displayOrder: 800,
  },
  {
    id: "bohumschool-im-life-ec6262fa-78a3-447d-adeb-b48e945b103b",
    insurerSlug: "im-life",
    insurerName: "iM라이프",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/im/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/im/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-kb-life-95197309-aa50-4c95-8ec3-23e8c3ce009c",
    insurerSlug: "kb-life",
    insurerName: "KB라이프",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서(개인)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/kb/claim-form-individual-.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/kb/claim-form(individual).pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-kb-life-bb210cb9-f9a8-4f77-8613-35582f66992f",
    insurerSlug: "kb-life",
    insurerName: "KB라이프",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서(법인)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/kb/claim-form-corporate-.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/kb/claim-form(corporate).pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-kb-insurance-8da0aa23-d7a9-4fc5-b63c-f5291fb2bac7",
    insurerSlug: "kb-insurance",
    insurerName: "KB손해보험",
    categoryLabel: "상해/질병/재물배상",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/kb/damage-illness-property/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/kb/damage-illness-property/claim-form.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-kb-insurance-4e41df33-b0e5-4866-8567-29b8d42b7eb0",
    insurerSlug: "kb-insurance",
    insurerName: "KB손해보험",
    categoryLabel: "상해/질병/재물배상",
    label: "보험금청구서(반려동물)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/kb/damage-illness-property/claim-form-pet.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/kb/damage-illness-property/claim-form-pet.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-kb-insurance-3cd68d01-20c4-4478-b402-e80ccb408035",
    insurerSlug: "kb-insurance",
    insurerName: "KB손해보험",
    categoryLabel: "상해/질병/재물배상",
    label: "보험금청구서(재물/배상책임)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/kb/damage-illness-property/claim-form-damage.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/kb/damage-illness-property/claim-form-damage.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-kb-insurance-dd13c947-b94e-4bda-97ea-e3dae445e7d9",
    insurerSlug: "kb-insurance",
    insurerName: "KB손해보험",
    categoryLabel: "자동차",
    label: "보험금청구서(자동차)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/kb/car/claim-form-car.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/kb/car/claim-form-car.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-kdb-life-f08b14a4-6479-4021-8df1-04ea37973e15",
    insurerSlug: "kdb-life",
    insurerName: "KDB생명",
    categoryLabel: "보험금청구서류",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/kdb/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/kdb/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-nh-life-84773f93-6996-4bf8-a4c1-78ead281ab7c",
    insurerSlug: "nh-life",
    insurerName: "NH농협생명",
    categoryLabel: "사고보험금 청구서",
    label: "보험금청구서(고연령,만65세이상)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/nh/accident-insurance-claim-form/insurance-claim-form--for-seniors_65-and-older-.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/nh/accident-insurance-claim-form/insurance-claim-form-(for-seniors_65-and-older).pdf",
    displayOrder: 10,
  },
  {
    id: "bohumschool-nh-life-5c6abf19-a271-4967-9469-2a66c8c0c5b4",
    insurerSlug: "nh-life",
    insurerName: "NH농협생명",
    categoryLabel: "사고보험금 청구서",
    label: "보험금청구서(일반고객)",
    category: "other",
    href: "/claim-forms/bohumschool/life_insurance/nh/accident-insurance-claim-form/insurance-claim-form--general-customers-.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/life_insurance/nh/accident-insurance-claim-form/insurance-claim-form-(general-customers).pdf",
    displayOrder: 10,
  },
  {
    id: "bohumschool-nh-general-b7e19361-0f11-43bd-9b8f-32fb451ea8a9",
    insurerSlug: "nh-general",
    insurerName: "NH농협손해보험",
    categoryLabel: "공통",
    label: "보험금청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/nh/common/claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/nh/common/claim-form.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-nh-general-fc29575a-50c7-478a-9520-aca5599b46c7",
    insurerSlug: "nh-general",
    insurerName: "NH농협손해보험",
    categoryLabel: "공통",
    label: "보험금청구서(반려동물)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/nh/common/claim-form-pet.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/nh/common/claim-form-pet.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-nh-general-15db421c-841d-4dcf-b110-66633ffc89b2",
    insurerSlug: "nh-general",
    insurerName: "NH농협손해보험",
    categoryLabel: "공통",
    label: "보험금청구서(큰글씨)",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/nh/common/claim-form-big-font.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/nh/common/claim-form-big-font.pdf",
    displayOrder: 100,
  },
  {
    id: "bohumschool-nh-general-da55c567-c041-4367-8c53-e6d47cd61859",
    insurerSlug: "nh-general",
    insurerName: "NH농협손해보험",
    categoryLabel: "상해/질병",
    label: "상해질병청구서류",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/nh/illness/illness-damage-claim-document.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/nh/illness/illness-damage-claim-document.pdf",
    displayOrder: 200,
  },
  {
    id: "bohumschool-nh-general-10eff5bf-ea90-4257-9af9-da5ebf75b94d",
    insurerSlug: "nh-general",
    insurerName: "NH농협손해보험",
    categoryLabel: "운전자",
    label: "운전자청구서류",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/nh/driver/driver-claim-document.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/nh/driver/driver-claim-document.pdf",
    displayOrder: 300,
  },
  {
    id: "bohumschool-nh-general-c0f4e494-4dd1-4cf0-bd08-51f33a85a135",
    insurerSlug: "nh-general",
    insurerName: "NH농협손해보험",
    categoryLabel: "여행자",
    label: "여행자청구서류",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/nh/travel/travel-claim-document.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/nh/travel/travel-claim-document.pdf",
    displayOrder: 400,
  },
  {
    id: "bohumschool-nh-general-9d70e8a0-def0-4455-a1e4-a058d94508a0",
    insurerSlug: "nh-general",
    insurerName: "NH농협손해보험",
    categoryLabel: "반려동물",
    label: "반려동물보험금청구서류",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/nh/pet/claim-form-pet.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/nh/pet/claim-form-pet.pdf",
    displayOrder: 500,
  },
  {
    id: "bohumschool-nh-general-28668e52-b707-438c-8523-ea8ba2e9bf00",
    insurerSlug: "nh-general",
    insurerName: "NH농협손해보험",
    categoryLabel: "골프",
    label: "골프보험청구서류",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/nh/golf/golf-claim-documents.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/nh/golf/golf-claim-documents.pdf",
    displayOrder: 600,
  },
  {
    id: "bohumschool-nh-general-82cff892-0021-4ae1-8a34-0b2ebdf7c79f",
    insurerSlug: "nh-general",
    insurerName: "NH농협손해보험",
    categoryLabel: "가축(소)",
    label: "가축(소)청구서류",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/nh/animal/livestock-cattle-claim-documents.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/nh/animal/livestock-cattle-claim-documents.pdf",
    displayOrder: 700,
  },
  {
    id: "bohumschool-thek-mutual-0a359e32-e434-44f5-a71a-8a70df6c0dcd",
    insurerSlug: "thek-mutual",
    insurerName: "TheK교직원공제",
    categoryLabel: "보험금청구서류",
    label: "종합복지급여 보험금 청구서",
    category: "other",
    href: "/claim-forms/bohumschool/fire_insurance/thek/comprehensive-welfare-benefit-insurance-claim-form.pdf",
    sourceUrl:
      "https://oomhivvzfyckwfubxveb.supabase.co/storage/v1/object/public/claim-docs/fire_insurance/thek/comprehensive-welfare-benefit-insurance-claim-form.pdf",
    displayOrder: 100,
  },
] satisfies ClaimFormFile[];
