import type { InsurerDirectoryEntry } from "./types";

export const insurerDirectoryEntries: InsurerDirectoryEntry[] = [
  // ──────────────────────────────────────────────
  // 손해보험 (Non-Life) Companies
  // ──────────────────────────────────────────────
  {
    id: "samsung-fire",
    name: "삼성화재",
    category: "non_life",
    officialWebsiteUrl: "https://www.samsungfire.com/",
    plannerPortalUrl: null,
    systemUrl: "https://erp.samsungfire.com/",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.samsungfire.com/v2/html/claim/01/C_010_030_001.html",
    termsUrl: "https://www.samsungfire.com/page/VH.REIF0011.do",
    customerCenterPhone: "1588-5114",
    helpdeskPhone: "1899-5005",
    callMonitoringPhone: "1566-0553",
    faxNumber: "0505-162-0872",
    claimFaxNumber: "0505-162-0872",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 영등포구 영등포로5길 19, 동아프라임밸리 504호 삼성화재 장기보험접수팀 (07275)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 설계사 카드수납\n[제휴사] KB국민, 롯데, BC, 삼성, 신한, 하나SK, 외환, NH농협, 씨티, 현대, 하나, 광주은행, 전북은행, 수협은행, 제주은행, 해외\n[1회성수납] 해당없음\n[신청 방법] 해당없음\n[카드 범위] 계약자 카드만 가능",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 100,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "hanwha-general",
    name: "한화손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.hwgeneralins.com/",
    plannerPortalUrl: null,
    systemUrl: "https://portal.hwgeneralins.com/",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.hwgeneralins.com/fplaza/compensation/receipt01.do",
    termsUrl:
      "https://www.hwgeneralins.com/notice/ir/product-ing01.do",
    customerCenterPhone: "1566-8000",
    helpdeskPhone: "02-316-0111",
    callMonitoringPhone: "1670-1882",
    faxNumber: "0502-779-1004",
    claimFaxNumber: "0502-779-1004",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 영등포구 은행로 30, 한화손해보험 장기보험심사팀 (07327)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 카드자동이체\n[제휴사] KB, BC, 신한, NH, 현대, 하나, 롯데, 삼성(삼성체크불가)\n[1회성수납] 콜센터\n[신청 방법] 고객센터 내방(콜센터 불가)\n[카드 범위] 계약자, 피보험자",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 105,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "hyundai-marine",
    name: "현대해상",
    category: "non_life",
    officialWebsiteUrl: "https://www.hi.co.kr/serviceAction.do",
    plannerPortalUrl: null,
    systemUrl:
      "https://sp.hi.co.kr/websquare/websquare.html?w2xPath=/common/xml/Login.xml",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.hi.co.kr/serviceAction.do?menuId=100631",
    termsUrl:
      "https://www.hi.co.kr/serviceAction.do?view=bin/PA/03/HHPA03010M#none",
    customerCenterPhone: "1588-5656",
    helpdeskPhone: "02-2628-4567",
    callMonitoringPhone: "1577-3223",
    faxNumber: "0507-774-6060",
    claimFaxNumber: "0507-774-6060",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 영등포구 국회대로 543, (당산동4가) 동양타워빌딩 7층 (07219)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 설계사 카드수납\n[제휴사] KB, 롯데, BC, 삼성, 신한, NH, 씨티, 현대, 하나\n[1회성수납] 콜센터\n[신청 방법] 해당없음\n[카드 범위] 계약자, 배우자, 직계존비속, 형제자매",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 110,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "meritz-fire",
    name: "메리츠화재",
    category: "non_life",
    officialWebsiteUrl: "https://www.meritzfire.com/",
    plannerPortalUrl: null,
    systemUrl:
      "https://nsso.meritzfire.com/LoginServer/loginFormPageMulti.jsp?InitechEamNoCacheNonce=B1F12BPyX1eGbk0rs8fDtA%3D%3D",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.meritzfire.com/compensation/longterm-insurance/request-document.do#!/",
    termsUrl:
      "https://www.meritzfire.com/disclosure/product-announcement/product-list.do#!/",
    customerCenterPhone: "1566-7711",
    helpdeskPhone: "02-3786-2777",
    callMonitoringPhone: "1577-7711",
    faxNumber: "0505-021-3400",
    claimFaxNumber: "0505-021-3400",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "경기 부천시 원미구 송내대로 80, 메리츠화재빌딩 6층 사고접수파트 (14623)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 카드자동이체\n[제휴사] BC, KB, 롯데, 삼성, 신한, 하나, 현대, NH\n[1회성수납] 콜센터\n[신청 방법] 계약후 고객 콜센터\n[카드 범위] 계약자, 배우자, 직계가족",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 115,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "db-general",
    name: "DB손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.idbins.com/FWMAIV0001.do#wrap",
    plannerPortalUrl: null,
    systemUrl: "https://www.mdbins.com/chrome.html",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.idbins.com/pc/bizxpress/ct/dc/FWCUSV1301.shtm",
    termsUrl: "https://www.idbins.com/FWMAIV1534.do",
    customerCenterPhone: "1588-0100",
    helpdeskPhone: "02-2262-1241",
    callMonitoringPhone: "1566-0757",
    faxNumber: "0505-181-4862",
    claimFaxNumber: "0505-181-4862",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "전북 전주시 완산구 서원로 99, 전주우체국 사서함 15호 DB손해보험 사고접수팀 (54966)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 설계사 카드수납\n[제휴사] KB, 롯데, BC, 삼성, 신한, 하나, NH, 현대\n[1회성수납] 콜센터\n[신청 방법] 해당없음\n[카드 범위] 계약자, 배우자, 직계존비속, 형제자매",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 120,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome"],
    verificationStatus: "needs_review",
  },
  {
    id: "kb-general",
    name: "KB손해보험",
    category: "non_life",
    officialWebsiteUrl:
      "https://www.kbinsure.co.kr/main.ec?mdmn=0101",
    plannerPortalUrl: null,
    systemUrl:
      "https://nsales.kbinsure.co.kr/eus/ch/ch_index.jsp",
    claimPageUrl: null,
    claimFormUrl: "https://www.kbinsure.co.kr/CG205020001.ec",
    termsUrl: "https://www.kbinsure.co.kr/CG802030001.ec",
    customerCenterPhone: "1544-0114",
    helpdeskPhone: "1544-8119",
    callMonitoringPhone: "1544-0019",
    faxNumber: "0505-136-6500",
    claimFaxNumber: "0505-136-6500",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 마포구 양화로 19, (합정동) KB손해보험 합정빌딩 19층 인보험사고접수센터 (04027)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 설계사 카드수납\n[제휴사] KB, 롯데, BC, 삼성, 신한, 우리, NH, 씨티, 현대, 하나\n[1회성수납] 해당없음\n[신청 방법] 해당없음\n[카드 범위] 계약자, 배우자, 직계가족",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 125,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "heungkuk-fire",
    name: "흥국화재",
    category: "non_life",
    officialWebsiteUrl: "https://www.heungkukfire.co.kr/",
    plannerPortalUrl: null,
    systemUrl: "https://sales.heungkukfire.co.kr/#/login",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.heungkukfire.co.kr/FRW/compensation/accidentDocInfo.do",
    termsUrl:
      "https://www.heungkukfire.co.kr/FRW/announce/insGoodsGongsiSale.do",
    customerCenterPhone: "1688-1688",
    helpdeskPhone: "031-786-8088",
    callMonitoringPhone: "1688-6997",
    faxNumber: "0504-800-0700",
    claimFaxNumber: "0504-800-0700",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울시 영등포구 버드나루로 2길 7, 흥국생명빌딩 9층 접수담당자 (07254)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 카드자동이체\n[제휴사] BC, 하나, KB, 삼성, 신한, 롯데, 현대, NH\n[1회성수납] 콜센터\n[신청 방법] 계약후 고객 콜센터\n[카드 범위] 계약자, 배우자, 직계가족",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 130,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "nh-general",
    name: "NH농협손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://nhfire.co.kr/",
    plannerPortalUrl: null,
    systemUrl:
      "https://ss.nhfire.co.kr/smartweb_prj/index_t.jsp",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.nhfire.co.kr/customer/bilgdcm/retrieveBilgDcmList.nhfire",
    termsUrl:
      "https://www.nhfire.co.kr/announce/productAnnounce/retrieveInsuranceProductsAnnounce.nhfire",
    customerCenterPhone: "1644-9000",
    helpdeskPhone: "1644-0090",
    callMonitoringPhone: "1644-9600",
    faxNumber: "0505-060-7000",
    claimFaxNumber: "0505-060-7000",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 서대문구 경기대로58, 경기빌딩 503호 농협손해보험 사고접수팀 (03736)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 카드자동이체\n[제휴사] NH, BC, KB, 신한, 삼성, 하나\n[1회성수납] 해당없음\n[신청 방법] 농협내방\n[카드 범위] 계약자 카드만 가능",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 135,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome"],
    verificationStatus: "needs_review",
  },
  {
    id: "lotte-general",
    name: "롯데손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.lotteins.co.kr/",
    plannerPortalUrl: null,
    systemUrl: "https://lottero.lotteins.co.kr/",
    claimPageUrl: null,
    claimFormUrl:
      "https://lotteins.co.kr/web/C/D/C/cdc_claim_0502.jsp",
    termsUrl: "https://lotteins.co.kr/web/C/D/H/cdh190.jsp",
    customerCenterPhone: "1588-3344",
    helpdeskPhone: "1599-8260",
    callMonitoringPhone: "1600-5182",
    faxNumber: "0507-333-9999",
    claimFaxNumber: "0507-333-9999",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 용산구 원효로90길 11, 용산더프라임빌딩 업무동 20층 롯데손해보험 장기사고접수파트(04315)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 설계사 카드수납\n[제휴사] BC, KB, NH, 롯데, 삼성, 신한, 씨티, 하나, 현대\n[1회성수납] 콜센터\n[신청 방법] 해당없음\n[카드 범위] 계약자, 배우자, 직계가족",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 140,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "aig-general",
    name: "AIG손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.aig.co.kr/wm/dpwmm001.html",
    plannerPortalUrl: null,
    systemUrl:
      "https://sso.aig.co.kr/gaLogin/gaLogin.jsp",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.aig.co.kr/wm/content.html?contentId=DPWMS406&menuId=MS406",
    termsUrl:
      "https://www.aig.co.kr/wo/dpwot001.html?menuId=MS702",
    customerCenterPhone: "1544-2792",
    helpdeskPhone: "02-2260-6855",
    callMonitoringPhone: "1600-4600",
    faxNumber: "02-2011-4607",
    claimFaxNumber: "02-2011-4607",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 영등포구 국제금융로 10, Two IFC 26층 AIG손해보험 보상본부 (07326)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 해당없음\n[수납] 카드자동이체\n[제휴사] KB, 롯데, BC, 삼성, 신한, 우리, 하나SK, 외환, NH, 씨티, 현대, 하나, 수협, 제주, 광주, 전북, 해외\n[1회성수납] 콜센터\n[신청 방법] 계약후 고객 콜센터\n[카드 범위] 계약자, 직계가족",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 145,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "chubb-general",
    name: "라이나손보",
    category: "non_life",
    officialWebsiteUrl: "https://www.chubb.com/kr-kr/",
    plannerPortalUrl: null,
    systemUrl:
      "https://ga.linagi.com/html/gap/GA/GAZ911M0.html",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.chubb.com/kr-kr/claims/report-a-claim.html",
    termsUrl:
      "https://www.chubb.com/kr-kr/disclosure/product.html",
    customerCenterPhone: "1566-5800",
    helpdeskPhone: "02-6922-5100",
    callMonitoringPhone: null,
    faxNumber: "02-2127-2308",
    claimFaxNumber: "02-2127-2308",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 종로구 종로6, 광화문 우체국 사서함 386(서린동) (03187)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 해당없음\n[수납] 카드자동이체\n[제휴사] 씨티, 한미, BC, 우리, 광주, 수협, 신협, 전북, 제주, 현대증권, 산업, 은련, 현대, 하나SK, 해외비자, 해외마스터, 해외JCB, 외환, 신한, 삼성, 롯데아맥스, 롯데, 농협, 국민\n[1회성수납] 콜센터\n[신청 방법] 계약후 고객 콜센터\n[카드 범위] 계약자, 배우자, 직계가족",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 150,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "yebyeol-general",
    name: "예별손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.yebyeol.co.kr/HO011010DM.scp",
    plannerPortalUrl: null,
    systemUrl:
      "https://mganet.mggeneralins.com/jsp/browserGuide.jsp",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.yebyeol.co.kr/RW031010DM.scp?menuId=MN0501020",
    termsUrl:
      "https://www.yebyeol.co.kr/PB031210DM.scp?menuId=MN0803006",
    customerCenterPhone: "1588-5959",
    helpdeskPhone: "02-3788-2261",
    callMonitoringPhone: "1577-3777",
    faxNumber: "0505-088-1646",
    claimFaxNumber: "0505-088-1646",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 영등포구 문래북로 56, 하스오토메이션코리아빌딩 6층 예별손해보험(주) 장기보험금접수센터 (07294)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 해당없음\n[수납] 설계사 카드수납\n[제휴사] KB, 하나(구외환), 비씨, 롯데, 삼성, 현대, 신한, NH\n[1회성수납] 콜센터\n[신청 방법] 해당없음\n[카드 범위] 계약자, 배우자, 자녀, 부모",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 155,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "hana-general",
    name: "하나손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.hanainsure.co.kr/",
    plannerPortalUrl: null,
    systemUrl: "https://sfa.saleshana.com/wq/login",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.hanainsure.co.kr/w/claim/healthReward/rewardDocCarGuide",
    termsUrl:
      "https://www.hanainsure.co.kr/w/disclosure/product/saleProduct",
    customerCenterPhone: "1566-3000",
    helpdeskPhone: "02-6670-8110",
    callMonitoringPhone: "02-6299-6821",
    faxNumber: "0505-152-0698",
    claimFaxNumber: "0505-152-0698",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 종로구 창경궁로 158, (인의동) 하나손해보험 보상팀 (03137)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "conditional",
    cardPaymentNote:
      "[구분] 초회만 가능\n[기타] 해당없음\n[수납] 해당없음\n[제휴사] KB, 롯데, BC, 삼성, 신한, 우리, 하나SK, 외환, NH, 씨티, 현대, 하나, 갤러리아\n[1회성수납] 콜센터\n[신청 방법] 해당없음\n[카드 범위] 계약자 카드만 가능",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 160,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome"],
    verificationStatus: "needs_review",
  },

  // ──────────────────────────────────────────────
  // 생명보험 (Life) Companies
  // ──────────────────────────────────────────────
  {
    id: "samsung-life",
    name: "삼성생명",
    category: "life",
    officialWebsiteUrl:
      "https://www.samsunglife.com/main/PDP-MAMAI000000M",
    plannerPortalUrl: null,
    systemUrl:
      "https://connectplus.samsunglife.com:10443/gasso/login",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.samsunglife.com/individual/mysamsunglife/insurance/internet/MDP-MYINT020110M",
    termsUrl:
      "https://www.samsunglife.com/individual/products/disclosure/sales/PDO-PRPRI010110M",
    customerCenterPhone: "1588-3114",
    helpdeskPhone: "02-311-4500",
    callMonitoringPhone: "1588-3115",
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress:
      "부산우체국 사서함 189호 삼성생명 사고보험금 접수담당자",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "conditional",
    cardPaymentNote:
      "[구분] 계속분만 가능\n[기타] 순수보장성만 가능\n[수납] 카드자동이체\n[제휴사] 삼성카드\n[1회성수납] 콜센터\n[신청 방법] 계약후 고객 콜센터\n[카드 범위] 계약자 카드만 가능",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 200,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "hanwha-life",
    name: "한화생명",
    category: "life",
    officialWebsiteUrl: "https://www.hanwhalife.com/index.jsp",
    plannerPortalUrl: null,
    systemUrl:
      "https://hmp.hanwhalife.com/online/solutions/websquare/websquare.html?w2xPath=/online/ui/uv/gmn/uvgmn010mvw.xml",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.hanwhalife.com/static/main/myPage/insurance/accident/document/MY_INAPADC_T10000.jsp",
    termsUrl:
      "https://www.hanwhalife.com/main/disclosure/goods/disclosurenotice/DF_GDDN000_P10000.do?MENU_ID1=DF_GDGL000",
    customerCenterPhone: "1588-6363",
    helpdeskPhone: "1522-6379",
    callMonitoringPhone: "1800-6633",
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress:
      "서울 마포구 마포대로 155, LG마포빌딩 3층 한화생명 사고보험금 우편청구 심사 담당자 (04143)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: null,
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 205,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "kyobo-life",
    name: "교보생명",
    category: "life",
    officialWebsiteUrl: "https://www.kyobo.com/",
    plannerPortalUrl: null,
    systemUrl: "https://ga.kyobo.com/",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.kyobo.com/dgt/web/customer/support/need-papers/list",
    termsUrl:
      "https://www.kyobo.com/dgt/web/product-official/all-product/search",
    customerCenterPhone: "1588-1001",
    helpdeskPhone: "02-721-3130",
    callMonitoringPhone: "1588-1636",
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress:
      "서울 영등포구 영등포로 96, 교보생명빌딩 6층, 교보생명 사고보험금 우편청구 담당자 (07291)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: null,
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 210,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "metlife",
    name: "메트라이프",
    category: "life",
    officialWebsiteUrl: "https://www.metlife.co.kr/",
    plannerPortalUrl: null,
    systemUrl: "https://metplus.metlife.co.kr/",
    claimPageUrl: null,
    claimFormUrl:
      "https://cyber.metlife.co.kr/claim/requiredDocumentNotice",
    termsUrl:
      "https://brand.metlife.co.kr/pn/paReal/insuProductDisclMain.do",
    customerCenterPhone: "1588-9600",
    helpdeskPhone: "1899-0751",
    callMonitoringPhone: "1588-9609",
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress:
      "서울 강남구 테헤란로 316, 메트라이프타워 클레임서비스팀 (06211)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: null,
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 215,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome"],
    verificationStatus: "needs_review",
  },
  {
    id: "nh-life",
    name: "NH농협생명",
    category: "life",
    officialWebsiteUrl: "https://www.nhlife.co.kr/main.nhl",
    plannerPortalUrl: null,
    systemUrl: "https://www.nhlife.co.kr/nhsmart.nhl",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.nhlife.co.kr/ho/cc/HOCC0010M00.nhl",
    termsUrl:
      "https://www.nhlife.co.kr/ho/on/HOON0004M00.nhl",
    customerCenterPhone: "1544-4000",
    helpdeskPhone: "02-3786-8800",
    callMonitoringPhone: "1544-4422",
    faxNumber: "02-6971-6040",
    claimFaxNumber: "02-6971-6040",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 마포구 마포대로 89, 서울마포우체국 사서함 13호 NH농협생명 지급심사 정보입력팀(다스카) (04156)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 카드자동이체\n[제휴사] BC, NH, 현대, 롯데\n[1회성수납] 콜센터\n[신청 방법] 계약후 고객 콜센터\n[카드 범위] 계약자",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 220,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "shinhan-life",
    name: "신한라이프",
    category: "life",
    officialWebsiteUrl:
      "https://www.shinhanlife.co.kr/hp/cdha0010.do",
    plannerPortalUrl: null,
    systemUrl:
      "https://ga.shinhanlife.co.kr:11043/colomga010m.msv",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.shinhanlife.co.kr/hp/cdhf0020t02.do",
    termsUrl:
      "https://www.shinhanlife.co.kr/hp/cdhi0040t01.do",
    customerCenterPhone: "1588-5580",
    helpdeskPhone: "02-3455-4119",
    callMonitoringPhone: "1522-2285",
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress:
      "서울 중구 소공로 70, 서울중앙우체국 사서함 160호 신한라이프 보험금접수 담당자 (04535)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: null,
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 225,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome"],
    verificationStatus: "needs_review",
  },
  {
    id: "kb-life",
    name: "KB라이프",
    category: "life",
    officialWebsiteUrl: "https://www.kblife.co.kr/",
    plannerPortalUrl: null,
    systemUrl:
      "https://sfa.kblife.co.kr/scr/m/sfa-login?request=sfaLogin",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.kblife.co.kr/customer-center/informRequiredDocument.do",
    termsUrl:
      "https://www.kblife.co.kr/customer-common/productList.do",
    customerCenterPhone: "1588-3374",
    helpdeskPhone: "1899-3899",
    callMonitoringPhone: "1566-2730",
    faxNumber: "02-6220-9912",
    claimFaxNumber: "02-6220-9912",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 영등포구 국제금융로 2길 28, KB금융타워 15층 보험금심사팀 (07325)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: null,
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 230,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "heungkuk-life",
    name: "흥국생명",
    category: "life",
    officialWebsiteUrl: "https://www.heungkuklife.co.kr/",
    plannerPortalUrl: null,
    systemUrl: "https://sales.heungkuklife.co.kr/",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.heungkuklife.co.kr/jsps/front/help/customer_require_tab.jsp",
    termsUrl:
      "https://www.heungkuklife.co.kr/jsps/front/help/customer_require_tab.jsp",
    customerCenterPhone: "1588-2288",
    helpdeskPhone: "031-786-8088",
    callMonitoringPhone: "1877-7066",
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress:
      "서울 영등포구 버드나루로2길 7, 2층 흥국생명 사고접수센터 (07254)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: null,
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 235,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome"],
    verificationStatus: "needs_review",
  },
  {
    id: "abl-life",
    name: "ABL생명",
    category: "life",
    officialWebsiteUrl: "https://www.abllife.co.kr/",
    plannerPortalUrl: null,
    systemUrl:
      "https://ga.abllife.co.kr/ui2/login/login.jsp",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.abllife.co.kr/st/custDesk/insSrvcGudn/acdtInsmClamGudn/acdtInsmClamGudn3?page=index",
    termsUrl:
      "https://www.abllife.co.kr/st/pban/prdtPban/whlPrdt/whlPrdt1/whlPrdt11?page=index",
    customerCenterPhone: "1588-6500",
    helpdeskPhone: "02-3787-8583",
    callMonitoringPhone: "1566-1002",
    faxNumber: "02-3299-5544",
    claimFaxNumber: "02-3299-5544",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 종로구 종로 400, 8층 (숭인동, ABL타워) 사고보험금 담당자 (03116)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: null,
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 240,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "miraeasset-life",
    name: "미래에셋생명",
    category: "life",
    officialWebsiteUrl:
      "https://life.miraeasset.com/home/index.do#MO-HO-000000-000000",
    plannerPortalUrl: null,
    systemUrl: "https://www.loveageplan.com/",
    claimPageUrl: null,
    claimFormUrl:
      "https://life.miraeasset.com/home/index.do#MO-HO-030501-010000",
    termsUrl:
      "https://life.miraeasset.com/micro/disclosure/product/PC-HO-080301-000000.do",
    customerCenterPhone: "1588-0220",
    helpdeskPhone: "02-3271-5108",
    callMonitoringPhone: "1588-0220",
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress:
      "서울 영등포구 선유로 49길 23, 아이에스비즈타워 13층 미래에셋생명 보험금 접수 담당자 (07208)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: null,
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 245,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "tongyang-life",
    name: "동양생명",
    category: "life",
    officialWebsiteUrl: "https://www.myangel.co.kr/",
    plannerPortalUrl: null,
    systemUrl: "https://1004.myangel.co.kr/",
    claimPageUrl: null,
    claimFormUrl: "https://www.myangel.co.kr/cscntr/csDocLst",
    termsUrl:
      "https://pbano.myangel.co.kr/paging/WE_AC_WEPAAP020100L",
    customerCenterPhone: "1577-1004",
    helpdeskPhone: "02-728-9900",
    callMonitoringPhone: "080-899-1004",
    faxNumber: "02-3289-4517",
    claimFaxNumber: "02-3289-4517",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 영등포구 선유로49길 23, 아이에스비즈타워 2차 12층 동양생명 보험심사팀 (07208)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 카드자동이체\n[제휴사] 신한, 현대, 삼성, 롯데, BC, KB\n[1회성수납] 콜센터\n[신청 방법] 계약후 고객 콜센터\n[카드 범위] 계약자",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 250,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome"],
    verificationStatus: "needs_review",
  },
  {
    id: "kdb-life",
    name: "KDB생명",
    category: "life",
    officialWebsiteUrl:
      "https://www.kdblife.co.kr/ajax.do?scrId=HDLMA002M02P",
    plannerPortalUrl: null,
    systemUrl: "https://kss.kdblife.co.kr/",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.kdblife.co.kr/ajax.do?scrId=HCSCT006M01P",
    termsUrl:
      "https://www.kdblife.co.kr/ajax.do?scrId=HDLMA002M02P",
    customerCenterPhone: "1588-4040",
    helpdeskPhone: "02-6303-2771",
    callMonitoringPhone: "1588-4040",
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress:
      "광주 서구 천변좌로 268, KDB생명빌딩 15층 사고보험금 우편청구 담당자 (61925)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: null,
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 255,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome"],
    verificationStatus: "needs_review",
  },
  {
    id: "db-life",
    name: "DB생명",
    category: "life",
    officialWebsiteUrl: "https://www.idblife.com/",
    plannerPortalUrl: null,
    systemUrl: "https://ga.idblife.com/",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.idblife.com/support/guide/acbf_clm",
    termsUrl: "https://www.idblife.com/notice/product/sale",
    customerCenterPhone: "1588-3131",
    helpdeskPhone: "02-2119-5151",
    callMonitoringPhone: "02-6470-7663",
    faxNumber: "0505-129-3134",
    claimFaxNumber: "0505-129-3134",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 성동구 아차산로 17길 48, SK V1 401호 DB생명 보험금 접수 담당자 (04799)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: null,
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 260,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "aia-life",
    name: "AIA생명",
    category: "life",
    officialWebsiteUrl:
      "https://www.aia.co.kr/ko/index.html",
    plannerPortalUrl: null,
    systemUrl: "https://imap.aia.co.kr/",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.aia.co.kr/ko/customer-support/customer-guide/forms/claims.html",
    termsUrl:
      "https://mypage.aia.co.kr/AIAHomepage/disclosure/our-products/selling/individual.do",
    customerCenterPhone: "1588-9898",
    helpdeskPhone: "1588-2937",
    callMonitoringPhone: "1588-2513",
    faxNumber: "02-2021-4540",
    claimFaxNumber: "02-2021-4540",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 중구 통일로 2길 16 (순화동 216) AIA타워 25층 AIA생명 보험금팀 (04511)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 보장성만 가능\n[수납] 카드자동이체\n[제휴사] 농협, 롯데, 국민, 비씨, 삼성, 신한, 씨티, 하나, 현대\n[1회성수납] 콜센터\n[신청 방법] 계약후 고객 콜센터\n[카드 범위] 계약자, 배우자, 직계존비속, 형제자매",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 265,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "im-life",
    name: "iM라이프",
    category: "life",
    officialWebsiteUrl: "https://www.dgbfnlife.com/main.do",
    plannerPortalUrl: null,
    systemUrl: "https://fgs.dgbfnlife.com:8443/",
    claimPageUrl: null,
    claimFormUrl:
      "https://www.dgbfnlife.com/BB/BB_D010.do",
    termsUrl: "https://www.dgbfnlife.com/BA/BA_A020.do",
    customerCenterPhone: "1588-4770",
    helpdeskPhone: "02-2087-9594",
    callMonitoringPhone: "1588-4770",
    faxNumber: "0505-083-5420",
    claimFaxNumber: "0505-083-5420",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울특별시 영등포구 양산로 91 리드원지식산업센터 3층 310호 iM라이프생명보험 보험금 접수센터 (07261)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: null,
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 270,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome"],
    verificationStatus: "needs_review",
  },
  {
    id: "lina-life",
    name: "라이나생명",
    category: "life",
    officialWebsiteUrl: "https://www.lina.co.kr/",
    plannerPortalUrl: null,
    systemUrl: "https://ga.lina.co.kr/html/gap/GA/GAZ911M0.html",
    claimPageUrl: null,
    claimFormUrl: null,
    termsUrl:
      "https://www.lina.co.kr/disclosure/product-public-announcement/product-guide",
    customerCenterPhone: "1588-0058",
    helpdeskPhone: "02-3781-2006",
    callMonitoringPhone: "1588-2442",
    faxNumber: "02-6944-1200",
    claimFaxNumber: "02-6944-1200",
    claimFaxHandlingType: "fax",
    mailingAddress:
      "서울 종로구 삼봉로 48, (청진동 188) 라이나타워 보험금 담당자 (03156)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote:
      "[구분] 초회, 계속분 가능\n[기타] 해당없음\n[수납] 카드자동이체\n[제휴사] BC, 신한, 국민, 삼성, 현대, 롯데, 하나, NH, 씨티\n[1회성수납] 콜센터\n[신청 방법] 해당없음\n[카드 범위] 계약자, 배우자, 직계존비속, 형제자매, 시부모, 사위, 며느리",
    sourceNote: "공개 출처 참고 후보 자료. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 275,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    supportedBrowsers: ["chrome","edge"],
    verificationStatus: "needs_review",
  },
  {
    id: "db-insurance",
    name: "DB손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.idbins.com/FWMAIV0001.do#wrap",
    plannerPortalUrl: null,
    systemUrl: "https://www.mdbins.com/chrome.html?ver=202605102342",
    claimPageUrl: null,
    claimFormUrl: "https://www.idbins.com/pc/bizxpress/ct/dc/FWCUSV1301.shtm",
    termsUrl: "https://www.idbins.com/FWMAIV1534.do",
    customerCenterPhone: "1588-0100",
    helpdeskPhone: "02-2262-1241",
    callMonitoringPhone: "1566-0757",
    faxNumber: "0505-181-4862",
    claimFaxNumber: "0505-181-4862",
    claimFaxHandlingType: "fax",
    mailingAddress: "전북 전주시 완산구 서원로 99, 전주우체국 사서함 15호 DB손해보험 사고접수팀 (54966)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote: "[구분] 초회, 계속분 가능\\n[기타] 보장성만 가능\\n[수납] 설계사 카드수납\\n[제휴사] KB국민카드, 롯데카드, BC카드, 삼성카드, 신한카드, 하나카드, NH농협카드, 현대카드\\n[1회성수납] 콜센터 통해 가능\\n[신청 방법] 해당사항 없음\\n[카드 범위] 계약자, 배우자, 직계존비속, 형제자매 가능",
    supportedBrowsers: ["chrome"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 120,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "kb-insurance",
    name: "KB손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.kbinsure.co.kr/main.ec?mdmn=0101",
    plannerPortalUrl: null,
    systemUrl: "https://nsales.kbinsure.co.kr/eus/ch/ch_index.jsp",
    claimPageUrl: null,
    claimFormUrl: "https://www.kbinsure.co.kr/CG205020001.ec",
    termsUrl: "https://www.kbinsure.co.kr/CG802030001.ec",
    customerCenterPhone: "1544-0114",
    helpdeskPhone: "1544-8119",
    callMonitoringPhone: "1544-0019",
    faxNumber: "0505-136-6500",
    claimFaxNumber: "0505-136-6500",
    claimFaxHandlingType: "fax",
    mailingAddress: "서울 마포구 양화로 19, (합정동) KB손해보험 합정빌딩 19층 인보험사고접수센터 (04027)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote: "[구분] 초회, 계속분 가능\\n[기타] 보장성만 가능\\n[수납] 설계사 카드수납\\n[제휴사] KB국민카드, 롯데카드, BC카드, 삼성카드, 신한카드, 우리카드, NH농협카드, 씨티카드, 현대카드, 하나카드\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 계약자, 배우자, 직계가족 가능",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 125,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "lotte-fire",
    name: "롯데손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.lotteins.co.kr/",
    plannerPortalUrl: null,
    systemUrl: "https://lottero.lotteins.co.kr/",
    claimPageUrl: null,
    claimFormUrl: "https://lotteins.co.kr/web/C/D/C/cdc_claim_0502.jsp",
    termsUrl: "https://lotteins.co.kr/web/C/D/H/cdh190.jsp",
    customerCenterPhone: "1588-3344",
    helpdeskPhone: "1599-8260",
    callMonitoringPhone: "1600-5182",
    faxNumber: "0507-333-9999",
    claimFaxNumber: "0507-333-9999",
    claimFaxHandlingType: "fax",
    mailingAddress: "서울 용산구 원효로90길 11, 용산더프라임빌딩 업무동 20층 롯데손해보험 장기사고접수파트(04315)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote: "[구분] 초회, 계속분 가능\\n[기타] 보장성만 가능\\n[수납] 설계사 카드수납\\n[제휴사] BC카드, KB국민카드, NH농협카드, 롯데카드, 삼성카드, 신한카드, 씨티카드, 하나카드, 현대카드\\n[1회성수납] 콜센터 통해 가능\\n[신청 방법] 해당없음\\n[카드 범위] 계약자, 배우자, 직계가족 카드 가능",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 140,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "lina-general",
    name: "라이나손보",
    category: "non_life",
    officialWebsiteUrl: "https://www.chubb.com/kr-kr/",
    plannerPortalUrl: null,
    systemUrl: "https://ga.linagi.com/html/gap/GA/GAZ911M0.html",
    claimPageUrl: null,
    claimFormUrl: "https://www.chubb.com/kr-kr/claims/report-a-claim.html",
    termsUrl: "https://www.chubb.com/kr-kr/disclosure/product.html",
    customerCenterPhone: "1566-5800",
    helpdeskPhone: "02-6922-5100",
    callMonitoringPhone: "해당사항 없음",
    faxNumber: "02-2127-2308",
    claimFaxNumber: "02-2127-2308",
    claimFaxHandlingType: "fax",
    mailingAddress: "서울 종로구 종로6, 광화문 우체국 사서함 386(서린동) (03187)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote: "[구분] 초회, 계속분 가능\\n[기타] 해당사항 없음\\n[수납] 카드 자동이체 가능\\n[제휴사] 씨티카드, 한미카드, BC카드, 우리카드, 광주카드, 수협카드, 신협카드, 전북카드, 제주카드, 현대증권카드, 산업카드, 은련카드, 현대카드, 하나SK카드, 해외비자, 해외마스터, 해외JCB, 외환카드, 신한카드, 삼성카드, 롯데아맥스, 롯데카드, 농협카드, 국민카드\\n[1회성수납] 콜센터 통해 가능\\n[신청 방법] 계약 후 고객이 콜센터 통해 신청\\n[카드 범위] 계약자, 배우자, 직계가족 가능",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 150,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "yebyeol-insurance",
    name: "예별손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.yebyeol.co.kr/HO011010DM.scp",
    plannerPortalUrl: null,
    systemUrl: "https://mganet.mggeneralins.com/jsp/browserGuide.jsp",
    claimPageUrl: null,
    claimFormUrl: "https://www.yebyeol.co.kr/RW031010DM.scp?menuId=MN0501020",
    termsUrl: "https://www.yebyeol.co.kr/PB031210DM.scp?menuId=MN0803006",
    customerCenterPhone: "1588-5959",
    helpdeskPhone: "02-3788-2261",
    callMonitoringPhone: "1577-3777",
    faxNumber: "0505-088-1646",
    claimFaxNumber: "0505-088-1646",
    claimFaxHandlingType: "fax",
    mailingAddress: "서울 영등포구 문래북로 56, 하스오토메이션코리아빌딩 6층 예별손해보험㈜ 장기보험금접수센터 (07294)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote: "[구분] 초회, 계속분 가능\\n[기타] 해당사항 없음\\n[수납] 설계사 카드수납\\n[제휴사] KB국민카드, 하나카드(구외환), 비씨카드,롯데카드 삼성카드,현대카드,신한카드,NH농협카드\\n[1회성수납] 콜센터 통해 가능\\n[신청 방법] 해당사항 없음\\n[카드 범위] 계약자, 배우자, 자녀, 부모 가능",
    supportedBrowsers: ["edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 155,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "chubb-life",
    name: "처브라이프생명",
    category: "life",
    officialWebsiteUrl: "https://www.chubblife.co.kr/",
    plannerPortalUrl: null,
    systemUrl: "https://esmart.chubblife.co.kr/index.do",
    claimPageUrl: null,
    claimFormUrl: "https://www.chubblife.co.kr/front/ctmcenter/insurance/listDocu.do",
    termsUrl: "https://www.chubblife.co.kr/front/official/sale/list.do",
    customerCenterPhone: "1599-4600",
    helpdeskPhone: "1599-4646",
    callMonitoringPhone: "1599-4600",
    faxNumber: "02-3480-7801 ",
    claimFaxNumber: "02-3480-7801",
    claimFaxHandlingType: "fax",
    mailingAddress: "서울 중구 세종대로 39, 10층 (남대문로4가, 대한상공회의소빌딩) 처브라이프생명 보험금지급팀 (04524)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote: "[구분] 초회, 계속분 가능\\n[기타] 보장성 상품 중 월보험료 15만원 이하 건(GA채널의 경우 전자서명 청약시 가능)\\n[수납] 수납 카드 자동이체 가능\\n[제휴사] 국내 전 카드사\\n[1회성수납] 해당없음\\n[신청 방법] 신계약 청약시 신청\\n[카드 범위] 계약자, 배우자, 직계가족 카드 가능",
    supportedBrowsers: ["edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 280,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "hana-life",
    name: "하나생명",
    category: "life",
    officialWebsiteUrl: "https://www.hanalife.co.kr/home/main.do",
    plannerPortalUrl: null,
    systemUrl: "https://ga.hanalife.co.kr/",
    claimPageUrl: null,
    claimFormUrl: "https://www.hanalife.co.kr/csc/accidentGuideRenew/accidentPaymentDocument.do",
    termsUrl: "https://hanalife.co.kr/anm/product/allProduct.do?status=on",
    customerCenterPhone: "1577-1112",
    helpdeskPhone: "02-3709-8602",
    callMonitoringPhone: "1577-1112",
    faxNumber: "02-6719-6722",
    claimFaxNumber: "02-6719-6722",
    claimFaxHandlingType: "fax",
    mailingAddress: "서울 중구 을지로 66, 하나생명 보험금 접수담당자 (04538) ",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 285,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "bnp-life",
    name: "BNP파리바카디프생명",
    category: "life",
    officialWebsiteUrl: "https://www.cardif.co.kr/",
    plannerPortalUrl: null,
    systemUrl: "https://ga.cardif.co.kr/",
    claimPageUrl: null,
    claimFormUrl: "https://www.cardif.co.kr/customer-center/hcwgi001.do",
    termsUrl: "https://www.cardif.co.kr/disclosure/papag101.do",
    customerCenterPhone: "1688-1118",
    helpdeskPhone: "1577-3435",
    callMonitoringPhone: "1688-1118",
    faxNumber: "콜센터 개별접수",
    claimFaxNumber: "콜센터 개별접수",
    claimFaxHandlingType: "fax",
    mailingAddress: "서울 영등포구 국회대로 612, 7층 또는 11층 BNP파리바카디프생명 보험금 담당자 (07258)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 290,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "fubonhyundai-life",
    name: "푸본현대생명",
    category: "life",
    officialWebsiteUrl: "https://www.fubonhyundai.com/",
    plannerPortalUrl: null,
    systemUrl: "https://ez.fubonhyundai.com/",
    claimPageUrl: null,
    claimFormUrl: "https://www.fubonhyundai.com/#CUSI070100000000",
    termsUrl: "https://www.fubonhyundai.com/#CUSI150102010101",
    customerCenterPhone: "1577-3311",
    helpdeskPhone: "080-860-1212",
    callMonitoringPhone: "-",
    faxNumber: "0505-106-0311",
    claimFaxNumber: "0505-106-0311",
    claimFaxHandlingType: "fax",
    mailingAddress: "서울 영등포구 여의나루로 57, 푸본현대생명 보험금팀 (07327)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: true,
    cardPaymentRecurringAvailable: true,
    cardPaymentStatus: "available",
    cardPaymentNote: "[구분] 초회, 계속분 가능\\n[기타] 보장성만 가능\\n[수납] 카드 자동이체 가능\\n[제휴사] 현대카드, BC카드, 신한카드, 국민카드\\n[1회성수납] 콜센터 통해 가능\\n[신청 방법] 계약 후 고객이 콜센터 통해 신청\\n[카드 범위] 계약자, 피보험자 가능",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 295,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "woochegook-mutual",
    name: "우체국보험",
    category: "non_life",
    officialWebsiteUrl: "https://epostlife.go.kr/MNDMDM0000.do",
    plannerPortalUrl: null,
    systemUrl: null,
    claimPageUrl: null,
    claimFormUrl: "https://epostlife.go.kr/PYIMRD0002.do",
    termsUrl: "https://epostlife.go.kr/ASISDM00AT.do",
    customerCenterPhone: "1599-0100",
    helpdeskPhone: null,
    callMonitoringPhone: null,
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress: "우편 청구 : 관할 우체국",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 300,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "suhyeop-mutual",
    name: "수협공제",
    category: "non_life",
    officialWebsiteUrl: "https://www.suhyup-bank.com/",
    plannerPortalUrl: null,
    systemUrl: null,
    claimPageUrl: null,
    claimFormUrl: "https://www.suhyup-bank.com/",
    termsUrl: "https://www.suhyup-bank.com/",
    customerCenterPhone: "1588-4119",
    helpdeskPhone: null,
    callMonitoringPhone: null,
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress: "서울 영등포구 은행로 54, 수협재단빌딩 (공제보상실 앞) (07241)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 305,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "thek-mutual",
    name: "TheK교직원공제",
    category: "non_life",
    officialWebsiteUrl: "https://www.ktcu.or.kr/index",
    plannerPortalUrl: null,
    systemUrl: null,
    claimPageUrl: null,
    claimFormUrl: "https://www.ktcu.or.kr/PPW-CSA-100101",
    termsUrl: "https://www.ktcu.or.kr/PPW-FIC-800301",
    customerCenterPhone: "1577-3993",
    helpdeskPhone: null,
    callMonitoringPhone: null,
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress: "서울특별시 영등포구 여의나루로 50, The-K한국교직원공제회 보험사업부 심사지원팀 (07328)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 310,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "shinhyeop-mutual",
    name: "신협공제",
    category: "non_life",
    officialWebsiteUrl: "https://openbank.cu.co.kr",
    plannerPortalUrl: null,
    systemUrl: null,
    claimPageUrl: null,
    claimFormUrl: "https://openbank.cu.co.kr/?sub=6000",
    termsUrl: "https://openbank.cu.co.kr/?sub=6000",
    customerCenterPhone: "1544-3030",
    helpdeskPhone: null,
    callMonitoringPhone: null,
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress: "대전 서구 한밭대로 745, 신협중앙회 17층 고객지원센터 보상지원 담당자 (35209)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 315,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "axa-insurance",
    name: "AXA손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.axa.co.kr/cui/index.html?screenID=SHCM0000&actionID=I01",
    plannerPortalUrl: null,
    systemUrl: null,
    claimPageUrl: null,
    claimFormUrl: "https://www.axa.co.kr/cui/cmk/cl/CMKCLL02M01.html?",
    termsUrl: "https://www.axa.co.kr/AsianPlatformInternet/html/axacms/common/intro/disclosure/insurance/index.html",
    customerCenterPhone: "1566-1566",
    helpdeskPhone: null,
    callMonitoringPhone: null,
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress: "서울 용산구 한강대로 71길 4, (갈월동) 한진중공업빌딩 10층 AXA손해보험㈜  (04322)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 400,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "samsung-digital",
    name: "삼성화재다이렉트착",
    category: "non_life",
    officialWebsiteUrl: "https://direct.samsungfire.com/",
    plannerPortalUrl: null,
    systemUrl: null,
    claimPageUrl: null,
    claimFormUrl: "https://www.samsungfire.com/vh/page/VH.HPCLA001.do",
    termsUrl: null,
    customerCenterPhone: "1577-3339",
    helpdeskPhone: null,
    callMonitoringPhone: null,
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress: "서울시 영등포구 영등포로 5길 19 동아프라임밸리 504호 삼성화재 장기보험접수팀 (07275)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 405,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "kakaopay-digital",
    name: "카카오페이손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://kakaopayinscorp.co.kr/",
    plannerPortalUrl: null,
    systemUrl: null,
    claimPageUrl: null,
    claimFormUrl: "https://kakaopayinscorp.co.kr/customer-center/claim-info",
    termsUrl: "https://kakaopayinscorp.co.kr/disclosure/goods?code=goods_list",
    customerCenterPhone: "1544-0022",
    helpdeskPhone: null,
    callMonitoringPhone: null,
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress: null,
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 410,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "kyobo-digital",
    name: "교보라이프플래닛",
    category: "non_life",
    officialWebsiteUrl: "https://www.lifeplanet.co.kr",
    plannerPortalUrl: null,
    systemUrl: null,
    claimPageUrl: null,
    claimFormUrl: "https://www.lifeplanet.co.kr/contact/pet/HPCG01S0.dev",
    termsUrl: "https://www.lifeplanet.co.kr/disclosure/good/HPDA01S0.dev",
    customerCenterPhone: "1566-0999",
    helpdeskPhone: null,
    callMonitoringPhone: null,
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress: "서울특별시 용산구 한강대로 35, 5층 교보라이프플래닛생명보험(주) 사고보험금 담당자 (04379)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 415,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "shinhanez-digital",
    name: "신한EZ손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.shinhanez.co.kr/static/man/MAIN0000M01.html",
    plannerPortalUrl: null,
    systemUrl: null,
    claimPageUrl: null,
    claimFormUrl: "https://www.shinhanez.co.kr/static/cus/CUS50000M01.html",
    termsUrl: "https://www.shinhanez.co.kr/static/pub/PUB2000T021.html",
    customerCenterPhone: "1544-2580",
    helpdeskPhone: null,
    callMonitoringPhone: null,
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress: "서울시 중구 남대문로 113 DB다동빌딩 4층 신한EZ손해보험 손해사정팀 (04522)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 420,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "carrot-digital",
    name: "캐롯손해보험",
    category: "non_life",
    officialWebsiteUrl: "https://www.carrotins.com/",
    plannerPortalUrl: null,
    systemUrl: null,
    claimPageUrl: null,
    claimFormUrl: "https://www.carrotins.com/desktop/reward/claim/guide",
    termsUrl: "https://www.carrotins.com/desktop/disclosure/sale/?afcDtFlgcd",
    customerCenterPhone: "1566-0300",
    helpdeskPhone: null,
    callMonitoringPhone: null,
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress: "서울특별시 중구 을지로2가 203 파인에비뉴 B동 20층 캐롯손해보험 디지털보험운영팀 (04551)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 425,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  },
  {
    id: "hanaoneday-digital",
    name: "하나원데이보험",
    category: "non_life",
    officialWebsiteUrl: "https://day.hanainsure.co.kr/oneday/main",
    plannerPortalUrl: null,
    systemUrl: null,
    claimPageUrl: null,
    claimFormUrl: "https://day.hanainsure.co.kr/p/reward/docGuide",
    termsUrl: "https://www.hanainsure.co.kr/w/disclosure/product/saleProduct",
    customerCenterPhone: "1566-3000",
    helpdeskPhone: null,
    callMonitoringPhone: null,
    faxNumber: null,
    claimFaxNumber: null,
    claimFaxHandlingType: "call_center_individual",
    mailingAddress: "서울특별시 종로구 종로 19, 9층 (종로1가, 하나손해보험) 보상접수담당자 (03161)",
    registeredMailAddress: null,
    cardPaymentInitialAvailable: false,
    cardPaymentRecurringAvailable: false,
    cardPaymentStatus: "unavailable",
    cardPaymentNote: "[구분] 해당사항 없음\\n[기타] 해당사항 없음\\n[수납] 해당사항 없음\\n[제휴사] 해당사항 없음\\n[1회성수납] 해당사항 없음\\n[신청 방법] 해당사항 없음\\n[카드 범위] 해당사항 없음",
    supportedBrowsers: ["chrome","edge"],
    sourceNote: "공개 출처(보험학교 아카이브) API 스크래핑 데이터. 공식 출처 재검수 필요.",
    notes: "공식 출처 검수 완료 전까지 고객 안내에 사용하지 마세요.",
    sortOrder: 430,
    isFeatured: false,
    isPublished: true,
    lastVerifiedAt: null,
    verificationStatus: "needs_review"
  }
];
