/**
 * PR-MESSAGE-01: Static public-safe customer message catalog (no DB required).
 * Only `safeCopy` is exposed on /message-templates — never `body` or admin fields.
 */

import {
  MessageTemplateAudienceType,
  MessageTemplateCategory,
  MessageTemplateChannel,
  MessageTemplateRiskLevel,
  MessageTemplateTone,
} from "@prisma/client";

import type { PublicMessageTemplate } from "@/lib/public/message-templates";

export type PublicMessageTemplateCatalogEntry = PublicMessageTemplate;

const VERIFIED = "2026-06-03";

export const publicMessageTemplateCatalog: PublicMessageTemplateCatalogEntry[] = [
  {
    id: "msg-pre-consultation-brief",
    title: "상담 전 안내",
    description: "상담 전 고객이 준비할 수 있도록 부담 없이 안내하는 문구입니다.",
    safeCopy:
      "안녕하세요, {고객명}님. 상담 전에 현재 궁금하신 부분을 간단히 정리해 두시면 상담 시간을 더 효율적으로 쓰실 수 있습니다. 무리하게 결정하시는 자리가 아니라, 현재 상황을 기준으로 필요한 부분을 함께 확인하는 시간으로 준비하겠습니다.",
    category: MessageTemplateCategory.greeting,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.new_customer,
    useCase: "상담 일정 확정 후, 미팅 전 고객 준비 안내",
    tone: MessageTemplateTone.warm,
    riskLevel: MessageTemplateRiskLevel.low,
    sortOrder: 10,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "msg-post-consultation-summary",
    title: "상담 후 요약",
    description: "상담 내용을 정리하고 결정을 서두르지 않도록 안내하는 문구입니다.",
    safeCopy:
      "오늘 상담 내용은 보장 범위, 유지 가능성, 중복 여부를 중심으로 정리해드렸습니다. 바로 결정하시기보다 안내드린 기준을 한 번 더 확인하신 뒤 편하게 말씀 주세요.",
    category: MessageTemplateCategory.follow_up,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.existing_customer,
    useCase: "대면·전화 상담 직후 후속 안내",
    tone: MessageTemplateTone.consultative,
    riskLevel: MessageTemplateRiskLevel.low,
    sortOrder: 20,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "claim-documents-request-neutral",
    title: "청구서류 확인 안내",
    description: "청구 전 필요 서류를 공식 기준으로 확인하도록 안내합니다.",
    safeCopy:
      "고객님, 청구 진행 전에 가입하신 상품과 보험사 기준에 맞는 필요 서류를 먼저 확인해 보겠습니다. 서류명과 제출 방법은 보험사별로 다를 수 있어 공식 안내 기준으로 다시 확인한 뒤 안내드리겠습니다.",
    category: MessageTemplateCategory.claim_guide,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.claim_customer,
    useCase: "청구 서류 준비 전 안내",
    tone: MessageTemplateTone.professional,
    riskLevel: MessageTemplateRiskLevel.medium,
    sortOrder: 30,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "msg-material-request-safe",
    title: "자료 확인 요청",
    description: "점검에 필요한 자료를 요청하되 민감정보는 가리도록 안내합니다.",
    safeCopy:
      "정확한 점검을 위해 현재 가입 내용을 확인할 수 있는 자료가 필요합니다. 민감한 개인정보는 가리고 보내주셔도 되며, 확인이 필요한 부분만 기준에 맞춰 정리해드리겠습니다.",
    category: MessageTemplateCategory.follow_up,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.existing_customer,
    useCase: "보장 점검·유지 검토 전 자료 확인",
    tone: MessageTemplateTone.careful,
    riskLevel: MessageTemplateRiskLevel.medium,
    sortOrder: 40,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "msg-schedule-confirm",
    title: "상담 일정 확인",
    description: "예정된 상담 일정을 차분하게 확인하는 문구입니다.",
    safeCopy:
      "고객님, 안내드린 상담 일정을 다시 확인드립니다. 일정에 변동이 있으시면 편하게 말씀 주세요. 상담에서는 현재 상황과 궁금하신 부분을 기준으로 차분히 확인해 드리겠습니다.",
    category: MessageTemplateCategory.appointment,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.general,
    useCase: "상담 하루 전 또는 일정 확정 직후",
    tone: MessageTemplateTone.neutral,
    riskLevel: MessageTemplateRiskLevel.low,
    sortOrder: 50,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "msg-schedule-reschedule",
    title: "상담 일정 변경 안내",
    description: "일정 변경 시 부담 없이 조율할 수 있도록 안내합니다.",
    safeCopy:
      "고객님, 일정 변경 요청 확인했습니다. 가능한 시간대를 알려주시면 다시 맞춰드리겠습니다. 급하게 진행하지 않아도 되니 편한 시간을 알려주세요.",
    category: MessageTemplateCategory.appointment,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.general,
    useCase: "고객 또는 설계사 일정 변경 시",
    tone: MessageTemplateTone.warm,
    riskLevel: MessageTemplateRiskLevel.low,
    sortOrder: 60,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "msg-no-response-gentle",
    title: "미응답 고객 재연락",
    description: "응답이 없는 고객에게 부담 없이 다시 안내하는 문구입니다.",
    safeCopy:
      "지난번 안내드린 내용은 급하게 결정하실 필요는 없습니다. 시간이 지나면 기준을 다시 확인해야 할 수 있어, 필요하실 때 편하게 말씀 주세요.",
    category: MessageTemplateCategory.follow_up,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.dormant_customer,
    useCase: "후속 연락 후 응답이 없을 때",
    tone: MessageTemplateTone.calm,
    riskLevel: MessageTemplateRiskLevel.low,
    sortOrder: 70,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "policy-review-meeting-reminder",
    title: "보장점검 미팅 리마인드",
    description: "보장점검 미팅 전 일정과 준비 사항을 안내합니다.",
    safeCopy:
      "고객님, 예정된 보장점검 미팅을 안내드립니다. 현재 가입 내용과 궁금하신 부분을 차분히 확인하는 시간으로 준비하겠습니다. 상품별 기준은 공식 자료를 함께 확인해 안내드리겠습니다.",
    category: MessageTemplateCategory.policy_review,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.existing_customer,
    useCase: "보장점검 미팅 전 리마인드",
    tone: MessageTemplateTone.reassuring,
    riskLevel: MessageTemplateRiskLevel.low,
    sortOrder: 80,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "msg-thanks-after-contact",
    title: "감사 인사",
    description: "상담·문의 후 감사 인사와 다음 확인 기준을 짧게 전달합니다.",
    safeCopy:
      "고객님, 시간 내어 확인해 주셔서 감사합니다. 안내드린 내용은 참고용이며, 최종 기준은 상품 약관과 보험사 공식 안내를 함께 확인해 주세요. 추가로 궁금하신 점이 있으시면 편하게 말씀 주세요.",
    category: MessageTemplateCategory.customer_care,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.general,
    useCase: "상담·문의 종료 후 감사 인사",
    tone: MessageTemplateTone.warm,
    riskLevel: MessageTemplateRiskLevel.low,
    sortOrder: 90,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "msg-disclosure-terms-check",
    title: "공시·약관 확인 안내",
    description: "공식 공시·약관 경로를 확인하도록 안내합니다.",
    safeCopy:
      "상품별 공시 자료와 약관 안내는 보험사 공식 경로에서 확인하시는 것이 가장 정확합니다. 필요하시면 함께 확인할 항목을 정리해드리겠습니다.",
    category: MessageTemplateCategory.notice,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.general,
    useCase: "공시·약관 확인이 필요할 때",
    tone: MessageTemplateTone.professional,
    riskLevel: MessageTemplateRiskLevel.low,
    sortOrder: 100,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "supplement-request-careful",
    title: "보완 확인 요청",
    description: "추가 확인이 필요할 때 정중히 요청하는 문구입니다.",
    safeCopy:
      "고객님, 안내드린 내용 중 추가 확인이 필요한 부분이 있어 정중히 요청드립니다. 보험사별 기준과 상품 조건에 따라 필요한 항목이 달라질 수 있으니, 공식 안내 기준을 확인한 뒤 필요한 범위만 다시 말씀드리겠습니다.",
    category: MessageTemplateCategory.claim_guide,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.claim_customer,
    useCase: "청구·상담 진행 중 추가 확인 필요",
    tone: MessageTemplateTone.careful,
    riskLevel: MessageTemplateRiskLevel.medium,
    sortOrder: 110,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "claim-completed-notice-concise",
    title: "처리 단계 완료 참고 안내",
    description: "처리 단계 완료 사실을 전달하되 결과를 단정하지 않습니다.",
    safeCopy:
      "고객님, 확인 가능한 처리 단계가 완료되어 안내드립니다. 세부 내용은 보험사 공식 안내와 약관 기준에 따라 달라질 수 있으니, 필요하시면 함께 다시 확인해 드리겠습니다.",
    category: MessageTemplateCategory.follow_up,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.claim_customer,
    useCase: "보험사 처리 단계 완료 안내",
    tone: MessageTemplateTone.concise,
    riskLevel: MessageTemplateRiskLevel.medium,
    sortOrder: 120,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "consultation-schedule-warm",
    title: "상담 일정 조율",
    description: "상담 가능 시간을 조율할 때 사용하는 문구입니다.",
    safeCopy:
      "고객님, 편하신 시간에 맞춰 차분히 상담드리겠습니다. 가능한 일정 몇 가지를 알려주시면, 보장 내용과 궁금하신 부분을 미리 확인해 준비하겠습니다.",
    category: MessageTemplateCategory.appointment,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.general,
    useCase: "첫 상담 일정 조율",
    tone: MessageTemplateTone.warm,
    riskLevel: MessageTemplateRiskLevel.low,
    sortOrder: 130,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "referral-response-formal",
    title: "소개 고객 첫 응대",
    description: "소개받은 고객에게 첫 안내를 보낼 때 사용합니다.",
    safeCopy:
      "안녕하세요, 고객님. 소개로 연락드리게 되었습니다. 필요한 내용을 먼저 편하게 말씀해 주시면, 확인 가능한 범위에서 차분히 안내드리겠습니다. 상담 전 상품별 기준과 공식 자료를 확인해 준비하겠습니다.",
    category: MessageTemplateCategory.greeting,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.referral,
    useCase: "소개 고객 첫 연락",
    tone: MessageTemplateTone.formal,
    riskLevel: MessageTemplateRiskLevel.low,
    sortOrder: 140,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "long-time-no-contact-warm",
    title: "장기 미연락 고객 안부",
    description: "오랜 기간 연락이 없던 고객에게 부담 없이 안부를 전합니다.",
    safeCopy:
      "고객님, 그동안 잘 지내셨는지 안부 인사드립니다. 가입하신 보장이나 궁금하신 점을 다시 확인하고 싶으실 때 편하게 말씀해 주세요. 필요한 경우 공식 자료 기준으로 차분히 확인해 드리겠습니다.",
    category: MessageTemplateCategory.follow_up,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.dormant_customer,
    useCase: "장기 미연락 고객 안부·재점검 제안",
    tone: MessageTemplateTone.warm,
    riskLevel: MessageTemplateRiskLevel.low,
    sortOrder: 150,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
  {
    id: "cancellation-concern-careful",
    title: "해지 고민 확인 안내",
    description: "해지 전 확인 기준을 차분히 안내합니다.",
    safeCopy:
      "고객님, 해지 여부를 결정하시기 전 현재 보장 내용, 납입 상황, 해지 시 달라지는 부분을 먼저 확인해 보시는 것이 좋습니다. 상품별로 기준이 다를 수 있어 공식 자료를 기준으로 함께 살펴보겠습니다.",
    category: MessageTemplateCategory.cancellation_defense,
    channel: MessageTemplateChannel.kakao,
    audienceType: MessageTemplateAudienceType.cancellation_risk,
    useCase: "해지를 고민하는 고객 안내",
    tone: MessageTemplateTone.careful,
    riskLevel: MessageTemplateRiskLevel.medium,
    sortOrder: 160,
    publishedAt: VERIFIED,
    updatedAt: VERIFIED,
  },
];

/** Draft sample kept out of public catalog — used only in admin/static demos. */
export const publicMessageTemplateDraftSampleId = "claim-received-notice-draft";
