import type { WorkLinkReviewCandidate } from "./review-types";

/**
 * PR-BS-15 display fixtures — fictional placeholders only.
 * Complements PR-BS-14 admin mock rows with publishable/planner-visible samples.
 */
export const VERIFIED_WORK_LINK_DISPLAY_FIXTURES: readonly WorkLinkReviewCandidate[] = [
  {
    id: "mock-wl-pub-claim-005",
    title: "청구 안내 자료",
    insurerName: "예시 보험사 E",
    infoType: "claimGuide",
    targetUrl: "https://example.invalid/target/claim-guide",
    officialSourceUrl: "https://example.invalid/official/claim-guide",
    sourceLabel: "보험사 공식 청구 안내 (placeholder)",
    riskLevel: "high",
    reviewStatus: "published",
    visibilityScope: "public",
    lastVerifiedAt: "2026-05-20",
    staleAfterDays: 90,
    reviewNotePrivate: "Admin-only: 공개 범위 승인 mock",
  },
  {
    id: "mock-wl-pub-disclosure-006",
    title: "공시·약관 자료",
    insurerName: "예시 보험사 F",
    infoType: "disclosure",
    targetUrl: "https://example.invalid/target/disclosure",
    officialSourceUrl: "https://example.invalid/official/disclosure",
    sourceLabel: "보험사 공식 공시 (placeholder)",
    riskLevel: "medium",
    reviewStatus: "published",
    visibilityScope: "public",
    lastVerifiedAt: "2026-05-15",
    staleAfterDays: 90,
    reviewNotePrivate: null,
  },
  {
    id: "mock-wl-planner-cc-007",
    title: "고객센터 안내 (mock planner)",
    insurerName: "예시 보험사 G",
    infoType: "customerCenter",
    targetUrl: null,
    officialSourceUrl: "https://example.invalid/official/customer-center",
    sourceLabel: "보험사 공식 고객센터 안내 (placeholder)",
    riskLevel: "high",
    reviewStatus: "verified",
    visibilityScope: "planner",
    lastVerifiedAt: "2026-05-10",
    staleAfterDays: 60,
    reviewNotePrivate: "Admin-only: 번호는 공식 페이지에서 재확인",
    internalReviewNote: "Admin-only",
  },
  {
    id: "mock-wl-planner-payment-008",
    title: "납입 안내 (mock planner only)",
    insurerName: "예시 보험사 H",
    infoType: "paymentInfo",
    targetUrl: null,
    officialSourceUrl: "https://example.invalid/official/payment",
    sourceLabel: "보험사 공식 납입 안내 (placeholder)",
    riskLevel: "high",
    reviewStatus: "verified",
    visibilityScope: "planner",
    lastVerifiedAt: "2026-05-08",
    staleAfterDays: 60,
    reviewNotePrivate: "카드납 조건은 상품별 상이 — 확정 표현 금지",
  },
  {
    id: "mock-wl-pub-payment-blocked-009",
    title: "납입 안내 (mock public 차단)",
    insurerName: "예시 보험사 I",
    infoType: "paymentInfo",
    targetUrl: null,
    officialSourceUrl: "https://example.invalid/official/payment-pub",
    sourceLabel: "placeholder",
    riskLevel: "high",
    reviewStatus: "published",
    visibilityScope: "public",
    lastVerifiedAt: "2026-05-01",
    staleAfterDays: 60,
    reviewNotePrivate: null,
  },
];
